### ISSUE TITLE
pytrip-gui cannot import voxelplan type files on modern systems

### ISSUE THREAD

**Issue by nbassler** [pytrip/pytrip#13]
Possibly some artefact from wx widgets updates.  

Attempted on Debian Testing, fresh clone from git.

**Comment by grzanka** [comment]
Could you copy-paste the error message and provide some details, like output of the commands:
 * python -V
 * pip freeze
?

**Comment by nbassler** [comment]
bassler@kepler:~$ python -V
Python 2.7.12rc1
bassler@kepler:~$ pip freeze
Exception:
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/pip/basecommand.py", line 215, in main
    status = self.run(options, args)
  File "/usr/lib/python2.7/dist-packages/pip/commands/freeze.py", line 85, in run
    for line in freeze(**freeze_kwargs):
  File "/usr/lib/python2.7/dist-packages/pip/operations/freeze.py", line 35, in freeze
    dist.get_metadata_lines('dependency_links.txt')
  File "/usr/share/python-wheels/pkg_resources-0.0.0-py2.py3-none-any.whl/pkg_resources/__init__.py", line 1477, in get_metadata_lines
    return yield_lines(self.get_metadata(name))
  File "/usr/share/python-wheels/pkg_resources-0.0.0-py2.py3-none-any.whl/pkg_resources/__init__.py", line 1469, in get_metadata
    return self._get(self._fn(self.egg_info, name))
  File "/usr/share/python-wheels/pkg_resources-0.0.0-py2.py3-none-any.whl/pkg_resources/__init__.py", line 1580, in _get
    with open(path, 'rb') as stream:
IOError: [Errno 13] Permission denied: '/usr/local/lib/python2.7/dist-packages/python_dateutil-2.2-py2.7.egg/EGG-INFO/dependency_links.txt'
bassler@kepler:~$

**Comment by grzanka** [comment]
Looks like corrupted python installation.

**Comment by grzanka** [comment]
Moved to https://github.com/pytrip/pytripgui/issues/3
