### ISSUE TITLE
Module 'pytrip' has no attribute 'dicomhelper'

### ISSUE THREAD

**Issue by ant6** [pytrip/pytrip#178]
I created a virtualenv *dicom* and executed `pip install pytrip98`. Directory *dicom1* contains some *.dcm* diles.
```
(dicom) ➜  dicom2trip dicom1 
usage: dicom2trip [-h] [-v] [-V] dicom_folder ctx_basename
dicom2trip: error: the following arguments are required: ctx_basename
(dicom) ➜  dicom2trip dicom1 test1
Traceback (most recent call last):
  File "/home/ant6/.virtualenvs/dicom/bin/dicom2trip", line 11, in <module>
    sys.exit(main())
  File "/home/ant6/.virtualenvs/dicom/lib/python3.5/site-packages/pytrip/utils/dicom2trip.py", line 44, in main
    dcm = pt.dicomhelper.read_dicom_folder(args.dicom_folder)
AttributeError: module 'pytrip' has no attribute 'dicomhelper'
```

**Comment by ant6** [comment]
```
(dicom) ➜  pip freeze
cycler==0.10.0
matplotlib==1.5.3
numpy==1.11.2
pydicom==0.9.9
pyparsing==2.1.10
python-dateutil==2.6.0
pytrip98==1.2.0
pytz==2016.7
scipy==0.18.1
six==1.10.0

(dicom) ➜  uname -a
Linux ant6-VB-ubu 4.4.0-45-generic #66-Ubuntu SMP Wed Oct 19 14:12:37 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux

(dicom) ➜  python --version
Python 3.5.2
```

**Comment by nbassler** [comment]
confirmed.

**Comment by grzanka** [comment]
@ant6 can you check if it helped ?

**Comment by ant6** [comment]
@grzanka It works :)
