### ISSUE TITLE
Using cubeslice converter as a new user

### ISSUE THREAD

**Issue by ant6** [pytrip/pytrip#182]
As a new user, I install *pytrip* with *pip* in my *virtualenv* (named *dicom*) and try to use `cubeslice` on files created previously with `dicom2trip` command (in *~/Downloads* directory).
```
(dicom) ➜  Downloads cubeslice 
/home/ant6/.virtualenvs/dicom/lib/python3.5/site-packages/matplotlib/font_manager.py:273: UserWarning: Matplotlib is building the font cache using fc-list. This may take a moment.
  warnings.warn('Matplotlib is building the font cache using fc-list. This may take a moment.')
/home/ant6/.virtualenvs/dicom/lib/python3.5/site-packages/matplotlib/font_manager.py:273: UserWarning: Matplotlib is building the font cache using fc-list. This may take a moment.
  warnings.warn('Matplotlib is building the font cache using fc-list. This may take a moment.')
(dicom) ➜  Downloads cubeslice -h
usage: cubeslice [-h] [--data [DATA]] [--ct [CT]] [-f N] [-t M] [-H]
                 [-o OUTPUTDIR] [-v] [-V]

optional arguments:
  -h, --help            show this help message and exit
  --data [DATA]         data cube(dos, let etc)
  --ct [CT]             CT cube
  -f N, --from N        Output from slice number N
  -t M, --to M          Output up to slice number M
  -H, --HUbar           Add HU colour bar
  -o OUTPUTDIR, --outputdir OUTPUTDIR
                        Write resulting files to this directory.
  -v, --verbosity       increase output verbosity
  -V, --version         show program's version number and exit
(dicom) ➜  Downloads ll
total 63M
drwxrwx--- 2 ant6 ant6 4,0K lis 12 04:39 di
-rwxrwx--- 1 ant6 ant6  62M lis 14 14:17 None.ctx
-rwxrwx--- 1 ant6 ant6  319 lis 14 14:17 None.hed
(dicom) ➜  Downloads cubeslice None
usage: cubeslice [-h] [--data [DATA]] [--ct [CT]] [-f N] [-t M] [-H]
                 [-o OUTPUTDIR] [-v] [-V]
cubeslice: error: unrecognized arguments: None
(dicom) ➜  Downloads cubeslice --data None
Traceback (most recent call last):
  File "/home/ant6/.virtualenvs/dicom/bin/cubeslice", line 11, in <module>
    sys.exit(main())
  File "/home/ant6/.virtualenvs/dicom/lib/python3.5/site-packages/pytrip/utils/cubeslice.py", line 150, in main
    data_cube, data_basename = load_data_cube(args.data)
  File "/home/ant6/.virtualenvs/dicom/lib/python3.5/site-packages/pytrip/utils/cubeslice.py", line 63, in load_data_cube
    d.read(filename)
  File "/home/ant6/.virtualenvs/dicom/lib/python3.5/site-packages/pytrip/cube.py", line 661, in read
    self.read_trip_data_file(path)
  File "/home/ant6/.virtualenvs/dicom/lib/python3.5/site-packages/pytrip/cube.py", line 749, in read_trip_data_file
    if data_file_path.endswith('.gz'):
AttributeError: 'NoneType' object has no attribute 'endswith'
```
Also, giving inappropriate file name results in no info and error code 2:
```
(dicom) ➜  Downloads cubeslice --data None.ctx
(dicom) ➜  Downloads echo $?
2
(dicom) ➜  Downloads cubeslice --data None.ctsdd
(dicom) ➜  Downloads echo $?                    
2
```

**Comment by grzanka** [comment]
I see the point, error handling should be improved.

Please try again with `--ct` switch. What you are trying to visualise is *CT cube* (Hounsfield units, diagnostic image) not *data cube* (beam intensity, Grays)

**Comment by ant6** [comment]
Now it works :)
But some info, especially about converters usage here: https://pytrip.readthedocs.io/en/latest/user_guide.html#converters would be nice :)

**Comment by nbassler** [comment]
Yes, this should be improved. 
Some thoughts: 

Do we need --ct and --data at all?
I think the file type can be automatically discovered. The behaviour of cubeslice is pretty straighforward intuitive whether you provide both or just one of those data sets.
```
usage: cubeslice [-h] [-f N] [-t M] [-H]
                 [-o OUTPUTDIR] [-v] [-V] inputfile(s)
```

where inputfile(s) may be a single or two cubes (where one of the two should be a ctx cube)
