### ISSUE TITLE
cubeslice broken

### ISSUE THREAD

**Issue by nbassler** [pytrip/pytrip#198]
```
bassler@grgalt:~/Projects/shieldhit/test/26_voxel$ cubeslice --data myvox02.dos --ct ../../res/TST000/TST000000.ctx 
Traceback (most recent call last):
  File "/home/bassler/.local/bin/cubeslice", line 11, in <module>
    sys.exit(main())
  File "/home/bassler/.local/lib/python2.7/site-packages/pytrip/utils/cubeslice.py", line 158, in main
    logger.info("Cube 1 " + args.dos + " shape {:d} x {:d} x {:d}".format(data_cube.dimx, data_cube.dimy,
AttributeError: 'Namespace' object has no attribute 'dos'
bassler@grgalt:~/Projects/shieldhit/test/26_voxel$ 
```

**Comment by nbassler** [comment]
but it works if I leave the --ct argument away.

**Comment by grzanka** [comment]
which version of pytrip ? Can you type `cubeslice --version` ?

**Comment by nbassler** [comment]
1.2.2

Not sure what is going on, it seems to work if the filenames are identical or so, maybe related to unsyncronized headers or so. Anyway, a clearer error message would be helpful.

**Comment by grzanka** [comment]
Can you put here header of myvox02.dos ? Is it present in same directory as myvox02.dos ?

**Comment by nbassler** [comment]
working header: TST000000.hed (for .dos generated with TRiP)
```
version 1.2
modality CT
primary_view transversal
data_type integer
num_bytes 2
byte_order vms
patient_name TST000
slice_dimension 256
pixel_size 1.210938
slice_distance 3
slice_number 102
xoffset 0
dimx 256
yoffset 0
dimy 256
zoffset 0
dimz 102
```

Broken header TST000001.hed (and .dos generated from pymchelper ``` convertmc tripcube```
```
version 2.0
modality CT
created_by pytrip
creation_info create by pytrip
primary_view transversal
data_type integer
num_bytes 2
byte_order vms
patient_name Anonymeous
slice_dimension 102
pixel_size 0.121093802154
slice_distance -0.303921699524
slice_number 102
xoffset 0
dimx 256
yoffset 0
dimy 256
zoffset 0
dimz 102
z_table no
```

maybe mostly a pymchelper issue. Cubeslice could throw an error if something bogus is found.

**Comment by grzanka** [comment]
I agree that the error handling should be improved.  Cubeslice expects file `myvox02.hed` - is it present ?

**Comment by nbassler** [comment]
I renamed both the .dos and .hed to TST000001.*

I tried to copy TST000000.hed to TST000001.hed and load the two again, still broken.

**Comment by grzanka** [comment]
OK, I'll investigate but it can take me few days.

**Comment by nbassler** [comment]
TODO: check if issue persists

**Comment by grzanka** [comment]
version 1.2.4 of pytrip - problem exists
