### ISSUE TITLE
Investigate new versioneer release (0.18)

### ISSUE THREAD

**Issue by ant6** [pytrip/pytrip#215]
Builds fail:
```
Traceback (most recent call last):
  File "setup.py", line 116, in <module>
    version=get_version(),
  File "setup.py", line 89, in get_version
    setup_versioneer()
  File "setup.py", line 33, in setup_versioneer
    versioneer.get_version()
AttributeError: 'module' object has no attribute 'get_version'
```

**Comment by grzanka** [comment]
Temporary fix: https://github.com/DataMedSci/pymchelper/pull/187
