### ISSUE TITLE
dicom2trip: "xio-4.60.00-phantom-chest" doesn't convert

### ISSUE THREAD

**Issue by nbassler** [pytrip/pytrip#249]
from https://subversion.assembla.com/svn/slicerrt/trunk/SlicerRt/data/xio-4.60.00-phantom-chest

```
bassler@baslup:~/Projects/pytrip$ dicom2trip /local/dicom/xio-4.60.00-phantom-chest fo2 
Traceback (most recent call last):
  File "/home/bassler/.local/bin/dicom2trip", line 11, in <module>
    sys.exit(main())
  File "/home/bassler/.local/lib/python2.7/site-packages/pytrip/utils/dicom2trip.py", line 55, in main
    c.read_dicom(dcm)
  File "/home/bassler/.local/lib/python2.7/site-packages/pytrip/ctx.py", line 50, in read_dicom
    raise InputError("Data doesn't contain ct data")
pytrip.error.InputError: "Data doesn't contain ct data"




bassler@baslup:~/Projects/pytrip$ dicom2trip /local/dicom/xio-4.60.00-phantom-chest fo2 -V
1.3.1
```

**Comment by grzanka** [comment]
Its normal, this directory doesn't contain any DICOM files, see https://subversion.assembla.com/svn/slicerrt/trunk/SlicerRt/data/xio-4.60.00-phantom-chest/

You need to go deeper

Message printed to the user is ugly however.

**Comment by nbassler** [comment]
:blush: of course.

Works fine then (there are no rtss file in it)
