### ISSUE TITLE
Missing attribute in tripexecuter.py?

### ISSUE THREAD

**Issue by TokePrintz** [pytrip/pytrip#252]
Taking the example from http://pytrip.readthedocs.io/en/stable/examples.html#example-02-trip-execution, I get the following error:

Traceback (most recent call last):
  File "tripplan.py", line 77, in <module>
    my_trip.execute(my_plan)
  File "/usr/local/lib/python2.7/dist-packages/pytrip/tripexecuter/tripexecuter.py", line 132, in execute
    self.ini_execute()
  File "/usr/local/lib/python2.7/dist-packages/pytrip/tripexecuter/tripexecuter.py", line 153, in ini_execute
    self.convert_files_to_voxelplan()
  File "/usr/local/lib/python2.7/dist-packages/pytrip/tripexecuter/tripexecuter.py", line 783, in convert_files_to_voxelplan
    structures.write_to_trip(out_path + ".vdx")
AttributeError: VdxCube instance has no attribute 'write_to_trip'

I have modified only the respective paths to match mine (I want to later do funny things with multiple fields and changed CTs but you have to learn to crawl before you can walk).
TRiP is "installed" locally (added to $PATH).
PyTRiP is 1.3.1.

**Comment by nbassler** [comment]
let Toke fix this, good exercises for working with git :)
