### ISSUE TITLE
RayStation still unhappy dicom->trip->dicom conversion

### ISSUE THREAD

**Issue by nbassler** [pytrip/pytrip#266]
![img_20170227_145109](https://cloud.githubusercontent.com/assets/7140398/23364493/945f9a78-fcff-11e6-85a8-3d4f7dd687cc.jpg)

**Comment by nbassler** [comment]
happens already at CT level, without RTSTRUCT being loaded.

**Comment by nbassler** [comment]
( Could be a result of #257 and may be fixed by #271 )

**Comment by nbassler** [comment]
It persists in current master (to be 1.3.3):
```
Version: 4.6.100.4, Changeset: 66649
RaySearch.CoreUtilities.LogicalException: Unhandled exception re thrown, original stack is preserved in the InnerException property ---> System.ArgumentNullException: Value cannot be null.
Parameter name: input
   at System.Text.RegularExpressions.Regex.Match(String input)
   at RaySearch.CoreServices.ImportExport.DicomInterface.DicomFileQuery.GetPatients(String name, String id, List`1& allParsedPatients)
   at RaySearch.CorePlatform.Presentation.Actions.ImportExport.DicomQueryTask.QueryGetPatients_(List`1& patientInfoSummeries)
   at RaySearch.CorePlatform.Presentation.Actions.ImportExport.DicomQueryTask.DoWork_()
   at RaySearch.CorePlatform.Framework.AsyncTask`2.DoWorkNoThrowWrapper_()
   --- End of inner exception stack trace ---
   at RaySearch.CorePlatform.Presentation.CommonPO.ErrorHandlingUtil.ErrorHandling(Exception error, Boolean showWarning)
   at RaySearch.CorePlatform.Presentation.CommonPO.ErrorHandlingUtil.ErrorHandling(RayAsyncCompletedEventArgs eventArgs)
   at RaySearch.CorePlatform.Presentation.PatientPO.DicomImportTree.DicomTreePO.<>c__DisplayClassd.<SetPatientsFromSource_>b__a(Object sender, DicomQueryCompletedEventArgs e)
   at RaySearch.CorePlatform.Framework.AsyncTask`2.PostCompleted_(Object result)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
```

**Comment by nbassler** [comment]
@TokePrintz maybe eclipse may give more detailed info on what is wrong?

**Comment by grzanka** [comment]
I wonder if dicompyler is generating files that RayStation can consume.
Here is nice code to parse RPDOSE files: http://dicompyler-core.readthedocs.io/en/latest/_modules/dicompylercore/dicomparser.html

**Comment by nbassler** [comment]
Patient ID is missing in trip -> dicom converted file.

**Comment by nbassler** [comment]
looks like contours are missing too when converting trip2dicom

**Comment by nbassler** [comment]
![img_20170228_161810](https://cloud.githubusercontent.com/assets/7140398/23412239/400d4d22-fdd5-11e6-8399-3eca253d4fb4.jpg)

**Comment by nbassler** [comment]
Adding 
```roi_structure_roi.ReferencedFrameOfReferenceUID = rt_ref_frame_study_data.FrameOfReferenceUID```
results in new error:

"Error while importing [name]: One or more examinations could not be found"

**Comment by nbassler** [comment]
syncing more UIDs gives yet another error:

```
Version: 4.6.100.4, Changeset: 66649
RaySearch.CoreUtilities.LogicalException: Unhandled exception re thrown, original stack is preserved in the InnerException property ---> RaySearch.CoreUtilities.LogicalException: Unhandled exception re thrown, original stack is preserved in the InnerException property ---> System.AggregateException: One or more errors occurred. ---> System.AggregateException: One or more errors occurred. ---> System.AggregateException: An error occured while execute action DICOM Import ---> System.Exception: Error at < ROIServices\ShapeBasedInterpolator.cpp:77 >
--> Logical error: Failed assertion `axis_ >= 0 && axis_ <= 2 : axis must be 0, 1 or 2.'

   --- Unmanaged call stack ---
   ?AssertionFailed@Utilities@RaySearch@@YAXPEBD000H@Z
   ??0ShapeBasedInterpolator@ImageProcessing@CoreServices@RaySearch@@QEAA@AEBUPoint3I@3@AEBUPoint3D@3@1AEBV?$vector@NV?$allocator@N@std@@@std@@AEAVIProgressListener@CoreUtilities@3@H@Z
   ?computeRelativeVolumes@ComputeBinaryVolumeService@ImageProcessing@CoreServices@RaySearch@@SAXAEAV?$vector@EV?$allocator@E@std@@@std@@AEBUPoint3I@4@AEBUPoint3D@4@2AEBV?$vector@V?$vector@UPoint3D@RaySearch@@V?$allocator@UPoint3D@RaySearch@@@std@@@std@@V?$allocator@V?$vector@UPoint3D@RaySearch@@V?$allocator@UPoint3D@RaySearch@@@std@@@std@@@2@@6@AEBV?$vector@NV?$allocator@N@std@@@6@_N55AEAVIProgressListener@CoreUtilities@4@HN@Z
   DllCanUnloadNowInternal
   DllCanUnloadNowInternal
   DllCanUnloadNowInternal
   GetPrivateContextsPerfCounters
   DllCanUnloadNowInternal
   DllCanUnloadNowInternal
   DllCanUnloadNowInternal
   DllCanUnloadNowInternal
   GetPrivateContextsPerfCounters
   DllRegisterServerInternal
   BaseThreadInitThunk
   RtlUserThreadStart

   at RaySearch.CoreServices.ImageProcessingAdapters.ComputeBinaryVolumeServiceAdapter.ComputeRelativeVolumes(Byte[]& outputData, Point3`1 numberOfVoxels, Point3`1 cornerVoxelCenter, Point3`1 voxelSize, Point3`1[][] contours, Double[] sliceLocations, Boolean useHats, Boolean useTopAndBottomHats, Boolean getSliceLocationsFromContours, Int32 axis, Double sliceDistance)
   at RaySearch.CoreServices.ImageProcessing.ComputeBinaryVolumeService.ComputeBinaryVolume_()
   at RaySearch.CorePlatform.Presentation.PatientViews.ShapeConverter.GetBinaryRoi_(Shape shape, ImageStack imageStack, ComputeBinaryVolumeService computeBinaryVolumeService, Boolean getSliceLocationsFromContours)
   at RaySearch.CorePlatform.Presentation.PatientViews.ShapeConverter.GetRoiContourSetSliceAligned(Shape shape, ImageStack imageStack, Boolean allowExtraSliceLocations)
   at RaySearch.CorePlatform.Presentation.Actions.ImportExport.DomainModelFactories.StructureSetFactory.AddRoiGeometry_(ExaminationStructureSet examinationStructureSet, IEnumerable`1 currentContours, StructureSetROI currentROI, IDomainState patientState, GetRegionOfInterestDelegate getRegionOfInterest, RTStructureSetIOD rtStruct)
   at RaySearch.CorePlatform.Presentation.Actions.ImportExport.DomainModelFactories.StructureSetFactory.ImportToExaminationStructureSet_(ExaminationStructureSet examinationStructureSet, RTStructureSetIOD rtStruct, IDomainState patientState, GetRegionOfInterestDelegate getRegionOfInterest, GetRegionOfInterestDelegate getPointOfInterest)
   at RaySearch.CorePlatform.Presentation.Actions.ImportExport.DicomImport.DicomStructureSetImportObject.AttachRtStructToPatientModel(Study study, IList`1 examinations, IList`1 regionsOfInterest, IList`1 pointsOfInterest, IDictionary`2 roiMaterials)
   at RaySearch.CorePlatform.Presentation.Actions.ImportExport.DicomImport.DicomStructureSetImportObject.Attach(Study study)
   at RaySearch.CorePlatform.Presentation.Actions.ImportExport.DicomImport.DicomImportAttachAction.AttachAll_()
   at RaySearch.CorePlatform.Presentation.Actions.ImportExport.DicomImport.DicomImportAttachAction.DoWork_()
   at RaySearch.CorePlatform.Framework.Action.DoWorkSequence_()
   at RaySearch.CorePlatform.Framework.AsyncAction`2.RunAsync()
   at RaySearch.CorePlatform.Framework.ActionScheduler.RaySearch.CorePlatform.Framework.IChildActionScheduler.Execute(IAsyncAction asyncAction)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at RaySearch.CorePlatform.Framework.ActionScheduler.RaySearch.CorePlatform.Framework.IChildActionScheduler.Execute(IAsyncAction asyncAction)
   at RaySearch.CorePlatform.Framework.Action.ExecuteSubAction[T,U](AsyncAction`2 action)
   at RaySearch.CorePlatform.Presentation.Actions.ImportExport.DicomSeriesImportAction.ImportStructureSets_(IEnumerable`1 dicomSeriesInfos)
   at RaySearch.CorePlatform.Presentation.Actions.ImportExport.DicomSeriesImportAction.Import_()
   at RaySearch.CorePlatform.Presentation.Actions.ImportExport.DicomSeriesImportAction.DoWork_()
   at RaySearch.CorePlatform.Framework.Action.DoWorkSequence_()
   at RaySearch.CorePlatform.Framework.AsyncAction`2.RunAsync()
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at RaySearch.CorePlatform.Framework.ActionScheduler.<ExecuteAsync>d__8.MoveNext()
   --- End of inner exception stack trace ---
   at RaySearch.CorePlatform.Framework.ActionScheduler.<ExecuteAsync>d__8.MoveNext()
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   at System.Threading.Tasks.ContinuationResultTaskFromResultTask`2.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at RaySearch.CorePlatform.Presentation.CommonPO.ActionExecuter.<ExecuteAsync>d__6.MoveNext()
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   at RaySearch.CorePlatform.Presentation.PatientPO.DicomImportPM.<ImportDicomSeries>d__17.MoveNext()
   --- End of inner exception stack trace ---
   at RaySearch.CorePlatform.Presentation.CommonPO.ErrorHandlingUtil.ErrorHandling(Exception error, Boolean showWarning)
   at RaySearch.CorePlatform.Presentation.PatientPO.DicomImportPM.<ImportDicomSeries>d__17.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at RaySearch.CorePlatform.Presentation.PatientPO.DicomImportPM.<OnPositiveCommandExecuted_>d__27.MoveNext()
   --- End of inner exception stack trace ---
   at RaySearch.CorePlatform.Presentation.CommonPO.ErrorHandlingUtil.ErrorHandling(Exception error, Boolean showWarning)
   at RaySearch.CorePlatform.Presentation.PatientPO.DicomImportPM.<OnPositiveCommandExecuted_>d__27.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.<>c.<ThrowAsync>b__6_0(Object state)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
```

**Comment by okejdokej** [comment]
This are some UIDs that are the same at the CT and STRUCT objects. Maybe it helps:

...
STRUCT.ReferencedFrameOfReferenceSequence.Item_1.RTReferencedStudySequence.Item_1.ReferencedSOPInstanceUID = CT.StudyInstanceUID

STRUCT.ReferencedFrameOfReferenceSequence.Item_1.RTReferencedStudySequence.Item_1.RTReferencedSeriesSequence.Item_1.SeriesInstanceUID = CT.SeriesInstanceUID

STRUCT.StudyInstanceUID = CT.StudyInstanceUID

STRUCT. ReferencedStudySequence.Item_1.ReferencedSOPInstanceUID = CT.StudyInstanceUID

STRUCT.ReferencedFrameOfReferenceSequence.Item_1.FrameOfReferenceUID = CT.FrameOfReferenceUID

STRUCT.ReferencedFrameOfReferenceSequence.Item_1.RTReferencedStudySequence.Item_1.RTReferencedSeriesSequence.Item_1.SeriesInstanceUID = CT.SeriesInstanceUID

...

**Comment by nbassler** [comment]
@okejdokej thanks, this is helpful.

**Comment by nbassler** [comment]
will check if the eclipse issue possibly have resolved this issue.

**Comment by nbassler** [comment]
still fails with current master branch:

```
Version: 4.6.100.4, Changeset: 66649
RaySearch.CoreUtilities.LogicalException: Unhandled exception re thrown, original stack is preserved in the InnerException property ---> RaySearch.CoreUtilities.LogicalException: Unhandled exception re thrown, original stack is preserved in the InnerException property ---> System.AggregateException: One or more errors occurred. ---> System.AggregateException: One or more errors occurred. ---> System.AggregateException: An error occured while execute action DICOM Import ---> System.Exception: Error at < ROIServices\ShapeBasedInterpolator.cpp:77 >
--> Logical error: Failed assertion `axis_ >= 0 && axis_ <= 2 : axis must be 0, 1 or 2.'

   --- Unmanaged call stack ---
   ?AssertionFailed@Utilities@RaySearch@@YAXPEBD000H@Z
   ??0ShapeBasedInterpolator@ImageProcessing@CoreServices@RaySearch@@QEAA@AEBUPoint3I@3@AEBUPoint3D@3@1AEBV?$vector@NV?$allocator@N@std@@@std@@AEAVIProgressListener@CoreUtilities@3@H@Z
   ?computeRelativeVolumes@ComputeBinaryVolumeService@ImageProcessing@CoreServices@RaySearch@@SAXAEAV?$vector@EV?$allocator@E@std@@@std@@AEBUPoint3I@4@AEBUPoint3D@4@2AEBV?$vector@V?$vector@UPoint3D@RaySearch@@V?$allocator@UPoint3D@RaySearch@@@std@@@std@@V?$allocator@V?$vector@UPoint3D@RaySearch@@V?$allocator@UPoint3D@RaySearch@@@std@@@std@@@2@@6@AEBV?$vector@NV?$allocator@N@std@@@6@_N55AEAVIProgressListener@CoreUtilities@4@HN@Z
   DllCanUnloadNowInternal
   DllCanUnloadNowInternal
   DllCanUnloadNowInternal
   GetPrivateContextsPerfCounters
   DllCanUnloadNowInternal
   DllCanUnloadNowInternal
   DllCanUnloadNowInternal
   DllCanUnloadNowInternal
   GetPrivateContextsPerfCounters
   DllRegisterServerInternal
   BaseThreadInitThunk
   RtlUserThreadStart

   at RaySearch.CoreServices.ImageProcessingAdapters.ComputeBinaryVolumeServiceAdapter.ComputeRelativeVolumes(Byte[]& outputData, Point3`1 numberOfVoxels, Point3`1 cornerVoxelCenter, Point3`1 voxelSize, Point3`1[][] contours, Double[] sliceLocations, Boolean useHats, Boolean useTopAndBottomHats, Boolean getSliceLocationsFromContours, Int32 axis, Double sliceDistance)
   at RaySearch.CoreServices.ImageProcessing.ComputeBinaryVolumeService.ComputeBinaryVolume_()
   at RaySearch.CorePlatform.Presentation.PatientViews.ShapeConverter.GetBinaryRoi_(Shape shape, ImageStack imageStack, ComputeBinaryVolumeService computeBinaryVolumeService, Boolean getSliceLocationsFromContours)
   at RaySearch.CorePlatform.Presentation.PatientViews.ShapeConverter.GetRoiContourSetSliceAligned(Shape shape, ImageStack imageStack, Boolean allowExtraSliceLocations)
   at RaySearch.CorePlatform.Presentation.Actions.ImportExport.DomainModelFactories.StructureSetFactory.AddRoiGeometry_(ExaminationStructureSet examinationStructureSet, IEnumerable`1 currentContours, StructureSetROI currentROI, IDomainState patientState, GetRegionOfInterestDelegate getRegionOfInterest, RTStructureSetIOD rtStruct)
   at RaySearch.CorePlatform.Presentation.Actions.ImportExport.DomainModelFactories.StructureSetFactory.ImportToExaminationStructureSet_(ExaminationStructureSet examinationStructureSet, RTStructureSetIOD rtStruct, IDomainState patientState, GetRegionOfInterestDelegate getRegionOfInterest, GetRegionOfInterestDelegate getPointOfInterest)
   at RaySearch.CorePlatform.Presentation.Actions.ImportExport.DicomImport.DicomStructureSetImportObject.AttachRtStructToPatientModel(Study study, IList`1 examinations, IList`1 regionsOfInterest, IList`1 pointsOfInterest, IDictionary`2 roiMaterials)
   at RaySearch.CorePlatform.Presentation.Actions.ImportExport.DicomImport.DicomStructureSetImportObject.Attach(Study study)
   at RaySearch.CorePlatform.Presentation.Actions.ImportExport.DicomImport.DicomImportAttachAction.AttachAll_()
   at RaySearch.CorePlatform.Presentation.Actions.ImportExport.DicomImport.DicomImportAttachAction.DoWork_()
   at RaySearch.CorePlatform.Framework.Action.DoWorkSequence_()
   at RaySearch.CorePlatform.Framework.AsyncAction`2.RunAsync()
   at RaySearch.CorePlatform.Framework.ActionScheduler.RaySearch.CorePlatform.Framework.IChildActionScheduler.Execute(IAsyncAction asyncAction)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at RaySearch.CorePlatform.Framework.ActionScheduler.RaySearch.CorePlatform.Framework.IChildActionScheduler.Execute(IAsyncAction asyncAction)
   at RaySearch.CorePlatform.Framework.Action.ExecuteSubAction[T,U](AsyncAction`2 action)
   at RaySearch.CorePlatform.Presentation.Actions.ImportExport.DicomSeriesImportAction.ImportStructureSets_(IEnumerable`1 dicomSeriesInfos)
   at RaySearch.CorePlatform.Presentation.Actions.ImportExport.DicomSeriesImportAction.Import_()
   at RaySearch.CorePlatform.Presentation.Actions.ImportExport.DicomSeriesImportAction.DoWork_()
   at RaySearch.CorePlatform.Framework.Action.DoWorkSequence_()
   at RaySearch.CorePlatform.Framework.AsyncAction`2.RunAsync()
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at RaySearch.CorePlatform.Framework.ActionScheduler.<ExecuteAsync>d__8.MoveNext()
   --- End of inner exception stack trace ---
   at RaySearch.CorePlatform.Framework.ActionScheduler.<ExecuteAsync>d__8.MoveNext()
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   at System.Threading.Tasks.ContinuationResultTaskFromResultTask`2.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at RaySearch.CorePlatform.Presentation.CommonPO.ActionExecuter.<ExecuteAsync>d__6.MoveNext()
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   at RaySearch.CorePlatform.Presentation.PatientPO.DicomImportPM.<ImportDicomSeries>d__17.MoveNext()
   --- End of inner exception stack trace ---
   at RaySearch.CorePlatform.Presentation.CommonPO.ErrorHandlingUtil.ErrorHandling(Exception error, Boolean showWarning)
   at RaySearch.CorePlatform.Presentation.PatientPO.DicomImportPM.<ImportDicomSeries>d__17.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at RaySearch.CorePlatform.Presentation.PatientPO.DicomImportPM.<OnPositiveCommandExecuted_>d__27.MoveNext()
   --- End of inner exception stack trace ---
   at RaySearch.CorePlatform.Presentation.CommonPO.ErrorHandlingUtil.ErrorHandling(Exception error, Boolean showWarning)
   at RaySearch.CorePlatform.Presentation.PatientPO.DicomImportPM.<OnPositiveCommandExecuted_>d__27.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.<>c.<ThrowAsync>b__6_0(Object state)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
```
