### ISSUE TITLE
tripexecutor: executing trip does not work with python3

### ISSUE THREAD

**Issue by nbassler** [pytrip/pytrip#280]
```
Traceback (most recent call last):
  File "main.py", line 82, in <module>
    sys.exit(main(sys.argv[1:]))
  File "main.py", line 76, in main
    plan_simple(c, voi_ptv, dose=3.0, angles=plan_angles)
  File "/home/bassler/Projects/dasu01/trip.py", line 85, in plan_simple
    exe = pte.TripExecuter(ct_images.get_modified_images(plan))
  File "/home/bassler/Projects/pytrip/pytrip/ctimage.py", line 36, in get_modified_images
    for voi in plan.get_vois():
TypeError: iter() returned non-iterator of type 'VoiCollection'
```
this happens several times in the code

can maybe be fixed by e.g.:
substituting
```
for voi in plan.get_vois().vois
```
with 
```
for voi in plan.get_vois().vois
```
but it does not get nicer...

**Comment by nbassler** [comment]
@grzanka I vaguely remember having had this problem before. Do you recommend a proper way how to amend this?

**Comment by grzanka** [comment]
Interesting, can you show to reproduce the error ?

**Comment by nbassler** [comment]
try running example02 using python3

**Comment by grzanka** [comment]
I see now :/ An issue with porting iterator from py2 to py3. I can work on that now

**Comment by nbassler** [comment]
After PR #284, this python3 issue still remains: (no error in python2)

```
Traceback (most recent call last):
  File "main.py", line 82, in <module>
TRiP98> sis  * /delete
    sys.exit(main(sys.argv[1:]))
  File "main.py", line 76, in main
    plan_simple(c, voi_ptv, dose=3.0, angles=plan_angles)
  File "/home/bassler/Projects/dasu01/trip.py", line 87, in plan_simple
    exe.execute(plan)
  File "/home/bassler/Projects/pytrip/pytrip/tripexecuter/tripexecuter.py", line 134, in execute
    self.execute_simple()
  File "/home/bassler/Projects/pytrip/pytrip/tripexecuter/tripexecuter.py", line 161, in execute_simple
    self.run_trip()
  File "/home/bassler/Projects/pytrip/pytrip/tripexecuter/tripexecuter.py", line 611, in run_trip
    self.run_trip_local()
  File "/home/bassler/Projects/pytrip/pytrip/tripexecuter/tripexecuter.py", line 704, in run_trip_local
    answer_stderr = p.stderr.readline()
AttributeError: 'NoneType' object has no attribute 'readline'
```
