### ISSUE TITLE
Voi class: broken calculate_isocenter() method

### ISSUE THREAD

**Issue by Tibazz** [pytrip/pytrip#350]
I think the for loop is supposed to be:

```for key in range(len(self.slices)):```

**Comment by nbassler** [comment]
https://www.python.org/dev/peps/pep-0279/

TL;DR: don't do range(len()), but enumerate()

regarding:
https://github.com/pytrip/pytrip/blob/master/pytrip/vdx.py#L730
could be, have to check.

**Comment by nbassler** [comment]
confirmed:

```
>>> pt.__version__
u'1.5.1'
```

using TST000
```
import pytrip as pt
c = pt.CtxCube()
c.read("TST000000.ctx")
v = pt.VdxCube(c)
v.read("TST000000.vdx")
vv = v.vois[10]  # GTV in TST000000
vv.calculate_center()

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/bassler/.local/lib/python2.7/site-packages/pytrip/vdx.py", line 731, in calculate_center
    center, area = self.slices[key].calculate_center()
TypeError: object cannot be interpreted as an index
```
