### ISSUE TITLE
Fix string py3/py2 incompatibility

### ISSUE THREAD

**Issue by grzanka** [pytrip/pytrip#39]
It looks that pytrip code contains calls to `string.lstrip` which is valid in Python2 and was removed in Python3. This bug reveals itself when making attempt to read a cube from .hed file instead of .ctx file.

```
# grzanka at gajewski-dell in ~/PycharmProjects/pytrip on git:master ✖︎ [17:44:40]
→ cat tests/TST001/tst001000.hed
version 1.4
modality CT
created_by pytrip
creation_info created by pytrip;
primary_view transversal
data_type integer
num_bytes 2
byte_order vms
patient_name tst001
slice_dimension 512
pixel_size 0.60546875
slice_distance 1.0
slice_number 172
xoffset 0
dimx 512
yoffset 0
dimy 512
zoffset 0
dimz 172
z_table no

# grzanka at gajewski-dell in ~/PycharmProjects/pytrip on git:master ✖︎ [17:44:48]
→ cat tests/bug.py              
from pytrip import CtxCube

c = CtxCube()
c.read("tests/TST001/tst001000.hed")

# grzanka at gajewski-dell in ~/PycharmProjects/pytrip on git:master ✖︎ [17:44:50]
→ PYTHONPATH=. python tests/bug.py 
Traceback (most recent call last):
  File "tests/bug.py", line 4, in <module>
    c.read("tests/TST001/tst001000.hed")
  File "/home/grzanka/PycharmProjects/pytrip/pytrip/cube.py", line 403, in read
    self.read_trip_data_file(path)
  File "/home/grzanka/PycharmProjects/pytrip/pytrip/cube.py", line 426, in read_trip_data_file
    raise IOError("Header size and dose cube size are not consistent.")
IOError: Header size and dose cube size are not consistent.

# grzanka at gajewski-dell in ~/PycharmProjects/pytrip on git:master ✖︎ [17:44:53]
→ PYTHONPATH=. python3 tests/bug.py
Traceback (most recent call last):
  File "tests/bug.py", line 4, in <module>
    c.read("tests/TST001/tst001000.hed")
  File "/home/grzanka/PycharmProjects/pytrip/pytrip/cube.py", line 403, in read
    self.read_trip_data_file(path)
  File "/home/grzanka/PycharmProjects/pytrip/pytrip/cube.py", line 417, in read_trip_data_file
    self.read_trip_header_file(path)
  File "/home/grzanka/PycharmProjects/pytrip/pytrip/cube.py", line 413, in read_trip_header_file
    self.read_trip_header(content)
  File "/home/grzanka/PycharmProjects/pytrip/pytrip/cube.py", line 351, in read_trip_header
    self.created_by = string.lstrip(content[i], "created_by ")
AttributeError: 'module' object has no attribute 'lstrip'

```

**Comment by grzanka** [comment]
The same problem when reading .ctx file:

```
# grzanka at gajewski-dell in ~/PycharmProjects/pytrip on git:master ✖︎ [17:48:20]
→ cat tests/bug.py 
from pytrip import CtxCube

c = CtxCube()
c.read("tests/TST001/tst001000.ctx")

# grzanka at gajewski-dell in ~/PycharmProjects/pytrip on git:master ✖︎ [17:48:26]
→ PYTHONPATH=. python tests/bug.py 

# grzanka at gajewski-dell in ~/PycharmProjects/pytrip on git:master ✖︎ [17:48:33]
→ PYTHONPATH=. python3 tests/bug.py
Traceback (most recent call last):
  File "tests/bug.py", line 4, in <module>
    c.read("tests/TST001/tst001000.ctx")
  File "/home/grzanka/PycharmProjects/pytrip/pytrip/cube.py", line 403, in read
    self.read_trip_data_file(path)
  File "/home/grzanka/PycharmProjects/pytrip/pytrip/cube.py", line 417, in read_trip_data_file
    self.read_trip_header_file(path)
  File "/home/grzanka/PycharmProjects/pytrip/pytrip/cube.py", line 413, in read_trip_header_file
    self.read_trip_header(content)
  File "/home/grzanka/PycharmProjects/pytrip/pytrip/cube.py", line 351, in read_trip_header
    self.created_by = string.lstrip(content[i], "created_by ")
AttributeError: 'module' object has no attribute 'lstrip'
```
