### ISSUE TITLE
Travis job fails due to some versioning problem

### ISSUE THREAD

**Issue by grzanka** [pytrip/pytrip#427]
```
Traceback (most recent call last):
  File "setup.py", line 116, in <module>
    version=get_version(),
  File "setup.py", line 94, in get_version
    if '*@' in parsed_version[1]:
TypeError: 'Version' object does not support indexing
```

See https://travis-ci.org/pytrip/pytrip/builds/355578456?utm_source=email&utm_medium=notification

**Comment by grzanka** [comment]
Looks like introduced by new version of setuptools (39.0) https://pypi.org/project/setuptools/#history
see 
https://github.com/pypa/setuptools/commit/eeeb9b27fa48fccf2b5d52919eff1c75c4ad1718

and https://github.com/DataMedSci/mcpartools/issues/104
