### ISSUE TITLE
Cubeslice error

### ISSUE THREAD

**Issue by AHufnagl** [pytrip/pytrip#436]
Error using cubeslice. 
"""
ahufnagl@sirius:~/test_ckk143$ cubeslice --data sobp3085mm.1H.2Gy.dos.phys.dos 
Traceback (most recent call last):
  File "/usr/local/bin/cubeslice", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python2.7/dist-packages/pytrip/utils/cubeslice.py", line 157, in main
    data_cube, data_basename = load_data_cube(args.data)
  File "/usr/local/lib/python2.7/dist-packages/pytrip/utils/cubeslice.py", line 74, in load_data_cube
    d.read(filename)
  File "/usr/local/lib/python2.7/dist-packages/pytrip/cube.py", line 468, in read
    self._read_trip_data_file(datafile_path=datafile_path, header_path=header_path)
  File "/usr/local/lib/python2.7/dist-packages/pytrip/cube.py", line 521, in _read_trip_data_file
    data_dtype = np.dtype(self.format_str)
TypeError: data type "<" not understood
"""

**Comment by grzanka** [comment]
Is it possible to share the problematic file either via public or private channels ?

**Comment by nbassler** [comment]
@grzanka i have it. .dos was generated with our own 
```
--- This is TRiP98-64, Version 1310(compiled May 27 2014 19:45:59), (C) M.Kraemer@gsi.de ---
    @ trip(Linux #1 SMP Debian 4.9.82-1+deb9u2 (2018-02-21) 4.9.0-6-amd64).
```
and pytrip 2.1.0

**Comment by nbassler** [comment]
reason is, that the produced cube was of type "float" with 8 bytes. PyTRiP expected "double" in the header for that case.
Found also another bug on the way, where the sometimes the "format_str" was added twice. (i.e. "<dd", instead of "<d").

Patch on the way.
