### ISSUE TITLE
gd2dat fails on gd files exported from SPC

### ISSUE THREAD

**Issue by grzanka** [pytrip/pytrip#443]
```
# gd2dat -V
2.2.0

# gd2dat XXX/1H.H2O.MeV15000.um007818.spc.gd 1.dat -vvv

# Running the conversion scrip gd2dat.py
# Reading the file XXX/1H.H2O.MeV15000.um007818.spc.gd with gd2dat.py
Traceback (most recent call last):
  File "/home/grzanka/PycharmProjects/pytrip/pytrip/utils/gd2dat.py", line 300, in <module>
    sys.exit(main(sys.argv[1:]))
  File "/home/grzanka/PycharmProjects/pytrip/pytrip/utils/gd2dat.py", line 292, in main
    gd_data = ReadGd(args.gd_file, let=False, exp=True)
  File "/home/grzanka/PycharmProjects/pytrip/pytrip/utils/gd2dat.py", line 74, in __init__
    self.read()
  File "/home/grzanka/PycharmProjects/pytrip/pytrip/utils/gd2dat.py", line 169, in read
    ydat.append(float(ele[num]))
IndexError: list index out of range
```

**Comment by nbassler** [comment]
gd2dat and gd2agr could be moved into a separate project in pytrip.

gd also does 2-d plots. Obvious a class based on matplotlib which can open .gd files would be useful here, also should the user wish to modify the plot.
