### ISSUE TITLE
TRiP98FilePath() unexpected behaviour and possible bug

### ISSUE THREAD

**Issue by nbassler** [pytrip/pytrip#456]
```
>>> pt.__version__
u'2.3.1'

>>> import pytrip as pt
>>> from pytrip.util import TRiP98FilePath

>>> path = '/home/bassler/Projects/pytripgui/_test/fofofo.hed'
>>> TRiP98FilePath(path, pt.CtxCube).basename
'/home/bassler/Projects/pytripgui/_test/fofofo'
```
I expected `fofofo` as return.

Second issue:
```
>>> TRiP98FilePath(path, pt.VdxCube).basename
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/bassler/.local/lib/python2.7/site-packages/pytrip/util.py", line 79, in __init__
    self.data_file_extension = self.cube_type.data_file_extension
AttributeError: class VdxCube has no attribute 'data_file_extension'

```

**Comment by grzanka** [comment]
You are right - it should work also for paths, not only for filenames
