### ISSUE TITLE
vdx attributeError:  xoffset

### ISSUE THREAD

**Issue by jbrage** [pytrip/pytrip#461]
Files downloaded from: [HIT DICOM](https://github.com/SlicerRt/SlicerRtData/tree/master/HIT-C12-cubePhantom)

dicom2trip creates the header file: [jeppe.hed](https://github.com/pytrip/pytrip/files/2034723/jeppe.txt)

I'm able to manipulate the ctx file straight away but not the vdx file.

Using Ubuntu 16.04 and python2.7 and
```
import logging
import pytrip as pt
print(pt.__version__)

logging.basicConfig(level=logging.DEBUG)

# import the ct data
my_ctx = pt.CtxCube()
my_ctx.read("jeppe.ctx")
# matrix = my_ctx.cube

# my_vdx = pt.VdxCube(my_ctx)
my_vdx = pt.VdxCube()
my_vdx.read("jeppe.vdx")
```
gives the error
```
2.3.1
INFO:pytrip.util:Locating : jeppe.ctx as <pytrip.ctx.CtxCube object at 0x7ff3edf9b150>
INFO:pytrip.util:Found jeppe.hed
INFO:pytrip.util:Locating : jeppe.ctx as <pytrip.ctx.CtxCube object at 0x7ff3edf9b150>
INFO:pytrip.cube:Reading header filejeppe.hed
DEBUG:pytrip.cube:TRiP loaded offsets: -155.000013 -281.542992 0.000000
DEBUG:pytrip.cube:self.format_str: '<h'
DEBUG:pytrip.cube:self.format_str: '<h'
DEBUG:pytrip.cube:Format string:<h
INFO:pytrip.cube:Opening file: jeppe.ctx
INFO:pytrip.cube:Cube data points : 45088768
DEBUG:pytrip.vdx:VDX class creates new patient_id 20180524-113605
DEBUG:pytrip.vdx:Parsing VDX format 2.0
DEBUG:pytrip.vdx:Read VDX: thickness = 1.000000
Traceback (most recent call last):
  File "example_jeppe.py", line 16, in <module>
    my_vdx.read("jeppe.vdx")
  File "/usr/local/lib/python2.7/dist-packages/pytrip/vdx.py", line 218, in read
    self.read_vdx(path)
  File "/usr/local/lib/python2.7/dist-packages/pytrip/vdx.py", line 266, in read_vdx
    i = v.read_vdx(content, i)
  File "/usr/local/lib/python2.7/dist-packages/pytrip/vdx.py", line 960, in read_vdx
    i = s.read_vdx(content, i)
  File "/usr/local/lib/python2.7/dist-packages/pytrip/vdx.py", line 1237, in read_vdx
    i = c.read_vdx(content, i)
  File "/usr/local/lib/python2.7/dist-packages/pytrip/vdx.py", line 1479, in read_vdx
    self.contour.append([float(con_dat[0]) + self.cube.xoffset,
AttributeError: 'NoneType' object has no attribute 'xoffset'
```

**Comment by TokePrintz** [comment]
I can reproduce this error with two different .vdx files and using Jeppes provided script (so it is not related to the specific input file)

**Comment by TokePrintz** [comment]
But maybe give ctx cube as argument in when creating vdx cube? E.g. use `my_vdx = pt.VdxCube(my_ctx)` instead of `my_vdx = pt.VdxCube()`? Then at least it works for me. 

The masterminds behind the scene would have to explain further; I just know that it is stated in vdx.py:

> 
>     We strongly recommend to load a CT and/or a DOS cube first, see example below:
>     >>> import pytrip as pt
>     >>> c = pt.CtxCube()
>     >>> c.read("tests/res/TST003/tst003000.ctx.gz")
>     >>> v = pt.VdxCube(c)
>     >>> v.read("tests/res/TST003/tst003000.vdx")

**Comment by jbrage** [comment]
I tried with both but I did not notice the error message was different when I passed the argument.

Using ```my_vdx = pt.VdxCube(my_ctx)``` instead of ```my_vdx = pt.VdxCube()```
gives me

```
Traceback (most recent call last):
  File "test_jeppe.py", line 16, in <module>
    my_vdx.read("jeppe.vdx")
  File "/usr/local/lib/python2.7/dist-packages/pytrip/vdx.py", line 218, in read
    self.read_vdx(path)
  File "/usr/local/lib/python2.7/dist-packages/pytrip/vdx.py", line 266, in read_vdx
    i = v.read_vdx(content, i)
  File "/usr/local/lib/python2.7/dist-packages/pytrip/vdx.py", line 960, in read_vdx
    i = s.read_vdx(content, i)
  File "/usr/local/lib/python2.7/dist-packages/pytrip/vdx.py", line 1237, in read_vdx
    i = c.read_vdx(content, i)
  File "/usr/local/lib/python2.7/dist-packages/pytrip/vdx.py", line 1479, in read_vdx
    self.contour.append([float(con_dat[0]) + self.cube.xoffset,
ValueError: could not convert string to float: origin
```

**Comment by nbassler** [comment]
@TokePrintz yes, that is one thing. You should pass the CTX cube to VDX, since some information VDX needs which is stored in CTX header. But still some issues:

```
bassler@baslup:~/Projects/pytrip/temp$ python3
Python 3.6.5rc1 (default, Mar 14 2018, 06:54:23) 
[GCC 7.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import pytrip as pt
>>> c = pt.CtxCube()
>>> c.read("foobar")
>>> v = pt.VdxCube(c)
>>> v.read("foobar.vdx")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/bassler/.local/lib/python3.6/site-packages/pytrip/vdx.py", line 218, in read
    self.read_vdx(path)
  File "/home/bassler/.local/lib/python3.6/site-packages/pytrip/vdx.py", line 266, in read_vdx
    i = v.read_vdx(content, i)
  File "/home/bassler/.local/lib/python3.6/site-packages/pytrip/vdx.py", line 960, in read_vdx
    i = s.read_vdx(content, i)
  File "/home/bassler/.local/lib/python3.6/site-packages/pytrip/vdx.py", line 1237, in read_vdx
    i = c.read_vdx(content, i)
  File "/home/bassler/.local/lib/python3.6/site-packages/pytrip/vdx.py", line 1479, in read_vdx
    self.contour.append([float(con_dat[0]) + self.cube.xoffset,
ValueError: could not convert string to float: 'origin'
```

**Comment by nbassler** [comment]
oops :)

**Comment by TokePrintz** [comment]
Hmm, I see. Strange, I am not getting that error when using my vdx examples.

**Comment by nbassler** [comment]
I think the issue is, that the .vdx files contains POIs. This is incorrectly handled by VdxCube.write.

Question is then what does TRiP want for POIs? a single point or two points which is the same...
