### ISSUE TITLE
Installation of pytrip fails on Anaconda with python2.7

### ISSUE THREAD

**Issue by grzanka** [pytrip/pytrip#484]
To reproduce I've used debian8 with Anaconda installed

```
conda create --name pytrip python=2.7
conda activate pytrip
```

then:
```
(pytrip) root@9cf1911d8f61:/# pip install pytrip98==2.5.0
Collecting pytrip98==2.5.0
  Downloading https://files.pythonhosted.org/packages/ae/be/e85bb75cc8d231ae6f97bd6e8b20d58d2dd894f32960a6cf8a053f9abb87/pytrip98-2.5.0-cp27-cp27mu-manylinux1_x86_64.whl (191kB)
    100% |################################| 194kB 8.2MB/s 
Requirement already satisfied: numpy in /root/anaconda3/envs/pytrip/lib/python2.7/site-packages (from pytrip98==2.5.0) (1.15.4)
Requirement already satisfied: pydicom in /root/anaconda3/envs/pytrip/lib/python2.7/site-packages (from pytrip98==2.5.0) (1.2.0)
Collecting matplotlib<2.2.0 (from pytrip98==2.5.0)
  Using cached https://files.pythonhosted.org/packages/73/51/8778092bf96c040086d100734d5459708289658f4874b1e0104f098ed6b5/matplotlib-2.1.2-cp27-cp27mu-manylinux1_x86_64.whl
Requirement already satisfied: python-dateutil>=2.1 in /root/anaconda3/envs/pytrip/lib/python2.7/site-packages (from matplotlib<2.2.0->pytrip98==2.5.0) (2.7.5)
Collecting subprocess32 (from matplotlib<2.2.0->pytrip98==2.5.0)
  Using cached https://files.pythonhosted.org/packages/be/2b/beeba583e9877e64db10b52a96915afc0feabf7144dcbf2a0d0ea68bf73d/subprocess32-3.5.3.tar.gz
Collecting cycler>=0.10 (from matplotlib<2.2.0->pytrip98==2.5.0)
  Using cached https://files.pythonhosted.org/packages/f7/d2/e07d3ebb2bd7af696440ce7e754c59dd546ffe1bbe732c8ab68b9c834e61/cycler-0.10.0-py2.py3-none-any.whl
Requirement already satisfied: six>=1.10 in /root/anaconda3/envs/pytrip/lib/python2.7/site-packages (from matplotlib<2.2.0->pytrip98==2.5.0) (1.11.0)
Collecting backports.functools-lru-cache (from matplotlib<2.2.0->pytrip98==2.5.0)
  Using cached https://files.pythonhosted.org/packages/03/8e/2424c0e65c4a066e28f539364deee49b6451f8fcd4f718fefa50cc3dcf48/backports.functools_lru_cache-1.5-py2.py3-none-any.whl
Collecting pytz (from matplotlib<2.2.0->pytrip98==2.5.0)
  Using cached https://files.pythonhosted.org/packages/f8/0e/2365ddc010afb3d79147f1dd544e5ee24bf4ece58ab99b16fbb465ce6dc0/pytz-2018.7-py2.py3-none-any.whl
Collecting pyparsing!=2.0.4,!=2.1.2,!=2.1.6,>=2.0.1 (from matplotlib<2.2.0->pytrip98==2.5.0)
  Using cached https://files.pythonhosted.org/packages/71/e8/6777f6624681c8b9701a8a0a5654f3eb56919a01a78e12bf3c73f5a3c714/pyparsing-2.3.0-py2.py3-none-any.whl
Building wheels for collected packages: subprocess32
  Running setup.py bdist_wheel for subprocess32 ... error
  Complete output from command /root/anaconda3/envs/pytrip/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-install-Vlge41/subprocess32/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" bdist_wheel -d /tmp/pip-wheel-jzl00W --python-tag cp27:
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build/lib.linux-x86_64-2.7
  copying subprocess32.py -> build/lib.linux-x86_64-2.7
  running build_ext
  running build_configure
  checking for gcc... no
  checking for cc... no
  checking for cl.exe... no
  configure: error: in `/tmp/pip-install-Vlge41/subprocess32':
  configure: error: no acceptable C compiler found in $PATH
  See `config.log' for more details
  Traceback (most recent call last):
    File "<string>", line 1, in <module>
    File "/tmp/pip-install-Vlge41/subprocess32/setup.py", line 120, in <module>
      main()
    File "/tmp/pip-install-Vlge41/subprocess32/setup.py", line 114, in main
      'Programming Language :: Python :: Implementation :: CPython',
    File "/root/anaconda3/envs/pytrip/lib/python2.7/site-packages/setuptools/__init__.py", line 140, in setup
      return distutils.core.setup(**attrs)
    File "/root/anaconda3/envs/pytrip/lib/python2.7/distutils/core.py", line 151, in setup
      dist.run_commands()
    File "/root/anaconda3/envs/pytrip/lib/python2.7/distutils/dist.py", line 953, in run_commands
      self.run_command(cmd)
    File "/root/anaconda3/envs/pytrip/lib/python2.7/distutils/dist.py", line 972, in run_command
      cmd_obj.run()
    File "/root/anaconda3/envs/pytrip/lib/python2.7/site-packages/wheel/bdist_wheel.py", line 188, in run
      self.run_command('build')
    File "/root/anaconda3/envs/pytrip/lib/python2.7/distutils/cmd.py", line 326, in run_command
      self.distribution.run_command(command)
    File "/root/anaconda3/envs/pytrip/lib/python2.7/distutils/dist.py", line 972, in run_command
      cmd_obj.run()
    File "/root/anaconda3/envs/pytrip/lib/python2.7/distutils/command/build.py", line 127, in run
      self.run_command(cmd_name)
    File "/root/anaconda3/envs/pytrip/lib/python2.7/distutils/cmd.py", line 326, in run_command
      self.distribution.run_command(command)
    File "/root/anaconda3/envs/pytrip/lib/python2.7/distutils/dist.py", line 972, in run_command
      cmd_obj.run()
    File "/tmp/pip-install-Vlge41/subprocess32/setup.py", line 41, in run
      self.run_command(command)
    File "/root/anaconda3/envs/pytrip/lib/python2.7/distutils/cmd.py", line 326, in run_command
      self.distribution.run_command(command)
    File "/root/anaconda3/envs/pytrip/lib/python2.7/distutils/dist.py", line 972, in run_command
      cmd_obj.run()
    File "/tmp/pip-install-Vlge41/subprocess32/setup.py", line 26, in run
      raise RuntimeError(configure_command + ' failed.')
  RuntimeError: sh ./configure failed.
  
  ----------------------------------------
  Failed building wheel for subprocess32
  Running setup.py clean for subprocess32
Failed to build subprocess32
Installing collected packages: subprocess32, cycler, backports.functools-lru-cache, pytz, pyparsing, matplotlib, pytrip98
  Running setup.py install for subprocess32 ... error
    Complete output from command /root/anaconda3/envs/pytrip/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-install-Vlge41/subprocess32/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-record-hz9pIg/install-record.txt --single-version-externally-managed --compile:
    running install
    running build
    running build_py
    creating build
    creating build/lib.linux-x86_64-2.7
    copying subprocess32.py -> build/lib.linux-x86_64-2.7
    running build_ext
    running build_configure
    checking for gcc... no
    checking for cc... no
    checking for cl.exe... no
    configure: error: in `/tmp/pip-install-Vlge41/subprocess32':
    configure: error: no acceptable C compiler found in $PATH
    See `config.log' for more details
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-Vlge41/subprocess32/setup.py", line 120, in <module>
        main()
      File "/tmp/pip-install-Vlge41/subprocess32/setup.py", line 114, in main
        'Programming Language :: Python :: Implementation :: CPython',
      File "/root/anaconda3/envs/pytrip/lib/python2.7/site-packages/setuptools/__init__.py", line 140, in setup
        return distutils.core.setup(**attrs)
      File "/root/anaconda3/envs/pytrip/lib/python2.7/distutils/core.py", line 151, in setup
        dist.run_commands()
      File "/root/anaconda3/envs/pytrip/lib/python2.7/distutils/dist.py", line 953, in run_commands
        self.run_command(cmd)
      File "/root/anaconda3/envs/pytrip/lib/python2.7/distutils/dist.py", line 972, in run_command
        cmd_obj.run()
      File "/root/anaconda3/envs/pytrip/lib/python2.7/site-packages/setuptools/command/install.py", line 61, in run
        return orig.install.run(self)
      File "/root/anaconda3/envs/pytrip/lib/python2.7/distutils/command/install.py", line 563, in run
        self.run_command('build')
      File "/root/anaconda3/envs/pytrip/lib/python2.7/distutils/cmd.py", line 326, in run_command
        self.distribution.run_command(command)
      File "/root/anaconda3/envs/pytrip/lib/python2.7/distutils/dist.py", line 972, in run_command
        cmd_obj.run()
      File "/root/anaconda3/envs/pytrip/lib/python2.7/distutils/command/build.py", line 127, in run
        self.run_command(cmd_name)
      File "/root/anaconda3/envs/pytrip/lib/python2.7/distutils/cmd.py", line 326, in run_command
        self.distribution.run_command(command)
      File "/root/anaconda3/envs/pytrip/lib/python2.7/distutils/dist.py", line 972, in run_command
        cmd_obj.run()
      File "/tmp/pip-install-Vlge41/subprocess32/setup.py", line 41, in run
        self.run_command(command)
      File "/root/anaconda3/envs/pytrip/lib/python2.7/distutils/cmd.py", line 326, in run_command
        self.distribution.run_command(command)
      File "/root/anaconda3/envs/pytrip/lib/python2.7/distutils/dist.py", line 972, in run_command
        cmd_obj.run()
      File "/tmp/pip-install-Vlge41/subprocess32/setup.py", line 26, in run
        raise RuntimeError(configure_command + ' failed.')
    RuntimeError: sh ./configure failed.
    
    ----------------------------------------
Command "/root/anaconda3/envs/pytrip/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-install-Vlge41/subprocess32/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-record-hz9pIg/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /tmp/pip-install-Vlge41/subprocess32/
```

**Comment by grzanka** [comment]
Temporary workaround:

```
(pytrip) root@9cf1911d8f61:/# conda install subprocess32
Solving environment: done

## Package Plan ##

  environment location: /root/anaconda3/envs/pytrip

  added / updated specs: 
    - subprocess32


The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    subprocess32-3.5.3         |   py27h7b6447c_0          44 KB

The following NEW packages will be INSTALLED:

    subprocess32: 3.5.3-py27h7b6447c_0

Proceed ([y]/n)? y


Downloading and Extracting Packages
subprocess32-3.5.3   | 44 KB     | ################################################################################################################### | 100% 
Preparing transaction: done
Verifying transaction: done
Executing transaction: done
(pytrip) root@9cf1911d8f61:/# pip install pytrip98==2.5.0
Collecting pytrip98==2.5.0
  Using cached https://files.pythonhosted.org/packages/ae/be/e85bb75cc8d231ae6f97bd6e8b20d58d2dd894f32960a6cf8a053f9abb87/pytrip98-2.5.0-cp27-cp27mu-manylinux1_x86_64.whl
Requirement already satisfied: pydicom in /root/anaconda3/envs/pytrip/lib/python2.7/site-packages (from pytrip98==2.5.0) (1.2.0)
Requirement already satisfied: numpy in /root/anaconda3/envs/pytrip/lib/python2.7/site-packages (from pytrip98==2.5.0) (1.15.4)
Collecting matplotlib<2.2.0 (from pytrip98==2.5.0)
  Using cached https://files.pythonhosted.org/packages/73/51/8778092bf96c040086d100734d5459708289658f4874b1e0104f098ed6b5/matplotlib-2.1.2-cp27-cp27mu-manylinux1_x86_64.whl
Requirement already satisfied: python-dateutil>=2.1 in /root/anaconda3/envs/pytrip/lib/python2.7/site-packages (from matplotlib<2.2.0->pytrip98==2.5.0) (2.7.5)
Requirement already satisfied: subprocess32 in /root/anaconda3/envs/pytrip/lib/python2.7/site-packages (from matplotlib<2.2.0->pytrip98==2.5.0) (3.5.3)
Collecting cycler>=0.10 (from matplotlib<2.2.0->pytrip98==2.5.0)
  Using cached https://files.pythonhosted.org/packages/f7/d2/e07d3ebb2bd7af696440ce7e754c59dd546ffe1bbe732c8ab68b9c834e61/cycler-0.10.0-py2.py3-none-any.whl
Requirement already satisfied: six>=1.10 in /root/anaconda3/envs/pytrip/lib/python2.7/site-packages (from matplotlib<2.2.0->pytrip98==2.5.0) (1.11.0)
Collecting backports.functools-lru-cache (from matplotlib<2.2.0->pytrip98==2.5.0)
  Using cached https://files.pythonhosted.org/packages/03/8e/2424c0e65c4a066e28f539364deee49b6451f8fcd4f718fefa50cc3dcf48/backports.functools_lru_cache-1.5-py2.py3-none-any.whl
Collecting pytz (from matplotlib<2.2.0->pytrip98==2.5.0)
  Using cached https://files.pythonhosted.org/packages/f8/0e/2365ddc010afb3d79147f1dd544e5ee24bf4ece58ab99b16fbb465ce6dc0/pytz-2018.7-py2.py3-none-any.whl
Collecting pyparsing!=2.0.4,!=2.1.2,!=2.1.6,>=2.0.1 (from matplotlib<2.2.0->pytrip98==2.5.0)
  Using cached https://files.pythonhosted.org/packages/71/e8/6777f6624681c8b9701a8a0a5654f3eb56919a01a78e12bf3c73f5a3c714/pyparsing-2.3.0-py2.py3-none-any.whl
Installing collected packages: cycler, backports.functools-lru-cache, pytz, pyparsing, matplotlib, pytrip98
Successfully installed backports.functools-lru-cache-1.5 cycler-0.10.0 matplotlib-2.1.2 pyparsing-2.3.0 pytrip98-2.5.0 pytz-2018.7
(pytrip) root@9cf1911d8f61:/# python -V
Python 2.7.15 :: Anaconda, Inc.
(pytrip) root@9cf1911d8f61:/# python
Python 2.7.15 |Anaconda, Inc.| (default, Nov 13 2018, 23:04:45) 
[GCC 7.3.0] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import pytrip as pt
>>> pt.__version__
u'2.5.0'
>>> 
```

**Comment by grzanka** [comment]
@nbassler take a look please

**Comment by grzanka** [comment]
@ljelen can you check on docker with debian8 whether problem still exists ?

**Comment by grzanka** [comment]
It seems that matplotlib for python 2.7 (v 2.x) requires subprocess32 which do not have binary packages. On pure debian without gcc and python-dev installation of subprocess32 fails.

There are two solutions:
 - ask user to install pytrip98 on python2.7 having gcc and python-dev
 - reply only on matplotlib<2.x for python2
