### ISSUE TITLE
setupy.py requires numpy

### ISSUE THREAD

**Issue by ljelen** [pytrip/pytrip#507]
![image](https://user-images.githubusercontent.com/47323191/73494400-c1092e00-43b4-11ea-8aa9-6a85d2eee2f8.png)

**Comment by grzanka** [comment]
The same problem appears if one tries to install pytrip98 via pip on a pure system without numpy installed. See i.e. a try with docker, Ubuntu 14.04 with Python 3.4 and pip installed via apt:

```
root@89a443a8dce1:/# python3 -V
Python 3.4.3
root@89a443a8dce1:/# pip3 -V
pip 1.5.4 from /usr/lib/python3/dist-packages (python 3.4)
root@89a443a8dce1:/# pip3 install pytrip98
Downloading/unpacking pytrip98
  Downloading pytrip98-2.6.1.tar.gz (119kB): 119kB downloaded
  Running setup.py (path:/tmp/pip_build_root/pytrip98/setup.py) egg_info for package pytrip98
    Traceback (most recent call last):
      File "<string>", line 17, in <module>
      File "/tmp/pip_build_root/pytrip98/setup.py", line 26, in <module>
        import numpy as np
    ImportError: No module named 'numpy'
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):

  File "<string>", line 17, in <module>

  File "/tmp/pip_build_root/pytrip98/setup.py", line 26, in <module>

    import numpy as np

ImportError: No module named 'numpy'

----------------------------------------
Cleaning up...
Command python setup.py egg_info failed with error code 1 in /tmp/pip_build_root/pytrip98
Storing debug log for failure in /root/.pip/pip.log

```

**Comment by grzanka** [comment]
It is worth noting that the problem happens when installing "source package"

**Comment by grzanka** [comment]
@ljelen can you check if problem exists still ? It seems to be fixed with https://github.com/pytrip/pytrip/pull/535

**Comment by ljelen** [comment]
nope, seems to be solved
