### ISSUE TITLE
Numpy version inconsistency

### ISSUE THREAD

**Issue by grzanka** [pytrip/pytrip#523]
Let us assume that user has installed some old numpy version.
Installation of pytrip98 package will not update user's numpy.
Unfortunately code is crashing due to numpy ABI(?) incompatibility:
```
(base) grzanka@grzanka-VirtualBox:~/Downloads$ conda create --name pytriptest2 python=3.7
Collecting package metadata: done
Solving environment: done


==> WARNING: A newer version of conda exists. <==
  current version: 4.6.14
  latest version: 4.8.2

Please update conda by running

    $ conda update -n base -c defaults conda



## Package Plan ##

  environment location: /home/grzanka/.conda/envs/pytriptest2

  added / updated specs:
    - python=3.7


The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    pip-20.0.2                 |           py37_1         1.9 MB
    setuptools-45.1.0          |           py37_0         664 KB
    wheel-0.34.2               |           py37_0          49 KB
    ------------------------------------------------------------
                                           Total:         2.6 MB

The following NEW packages will be INSTALLED:

  _libgcc_mutex      pkgs/main/linux-64::_libgcc_mutex-0.1-main
  ca-certificates    pkgs/main/linux-64::ca-certificates-2020.1.1-0
  certifi            pkgs/main/linux-64::certifi-2019.11.28-py37_0
  ld_impl_linux-64   pkgs/main/linux-64::ld_impl_linux-64-2.33.1-h53a641e_7
  libedit            pkgs/main/linux-64::libedit-3.1.20181209-hc058e9b_0
  libffi             pkgs/main/linux-64::libffi-3.2.1-hd88cf55_4
  libgcc-ng          pkgs/main/linux-64::libgcc-ng-9.1.0-hdf63c60_0
  libstdcxx-ng       pkgs/main/linux-64::libstdcxx-ng-9.1.0-hdf63c60_0
  ncurses            pkgs/main/linux-64::ncurses-6.1-he6710b0_1
  openssl            pkgs/main/linux-64::openssl-1.1.1d-h7b6447c_3
  pip                pkgs/main/linux-64::pip-20.0.2-py37_1
  python             pkgs/main/linux-64::python-3.7.6-h0371630_2
  readline           pkgs/main/linux-64::readline-7.0-h7b6447c_5
  setuptools         pkgs/main/linux-64::setuptools-45.1.0-py37_0
  sqlite             pkgs/main/linux-64::sqlite-3.31.1-h7b6447c_0
  tk                 pkgs/main/linux-64::tk-8.6.8-hbc83047_0
  wheel              pkgs/main/linux-64::wheel-0.34.2-py37_0
  xz                 pkgs/main/linux-64::xz-5.2.4-h14c3975_4
  zlib               pkgs/main/linux-64::zlib-1.2.11-h7b6447c_3


Proceed ([y]/n)? y


Downloading and Extracting Packages
pip-20.0.2           | 1.9 MB    | ######################################################################################################################################################################## | 100% 
setuptools-45.1.0    | 664 KB    | ######################################################################################################################################################################## | 100% 
wheel-0.34.2         | 49 KB     | ######################################################################################################################################################################## | 100% 
Preparing transaction: done
Verifying transaction: done
Executing transaction: done
#
# To activate this environment, use
#
#     $ conda activate pytriptest2
#
# To deactivate an active environment, use
#
#     $ conda deactivate

(base) grzanka@grzanka-VirtualBox:~/Downloads$ conda activate pytriptest2
(pytriptest2) grzanka@grzanka-VirtualBox:~/Downloads$ pip install "numpy==1.15.4"
Collecting numpy==1.15.4
  Downloading numpy-1.15.4-cp37-cp37m-manylinux1_x86_64.whl (13.8 MB)
     |████████████████████████████████| 13.8 MB 273 kB/s 
Installing collected packages: numpy
  Attempting uninstall: numpy
    Found existing installation: numpy 1.17.3
    Uninstalling numpy-1.17.3:
      Successfully uninstalled numpy-1.17.3
Successfully installed numpy-1.15.4
(pytriptest2) grzanka@grzanka-VirtualBox:~/Downloads$ pip install pytrip98
Collecting pytrip98
  Downloading pytrip98-2.6.0-cp37-cp37m-manylinux1_x86_64.whl (214 kB)
     |████████████████████████████████| 214 kB 405 kB/s 
Collecting pydicom
  Using cached pydicom-1.4.1-py2.py3-none-any.whl (35.1 MB)
Requirement already satisfied: numpy in /home/grzanka/.conda/envs/pytriptest2/lib/python3.7/site-packages (from pytrip98) (1.15.4)
Collecting matplotlib
  Downloading matplotlib-3.1.3-cp37-cp37m-manylinux1_x86_64.whl (13.1 MB)
     |████████████████████████████████| 13.1 MB 163 kB/s 
Collecting pyparsing!=2.0.4,!=2.1.2,!=2.1.6,>=2.0.1
  Using cached pyparsing-2.4.6-py2.py3-none-any.whl (67 kB)
Collecting cycler>=0.10
  Using cached cycler-0.10.0-py2.py3-none-any.whl (6.5 kB)
Collecting python-dateutil>=2.1
  Using cached python_dateutil-2.8.1-py2.py3-none-any.whl (227 kB)
Collecting kiwisolver>=1.0.1
  Downloading kiwisolver-1.1.0-cp37-cp37m-manylinux1_x86_64.whl (90 kB)
     |████████████████████████████████| 90 kB 120 kB/s 
Collecting six
  Using cached six-1.14.0-py2.py3-none-any.whl (10 kB)
Requirement already satisfied: setuptools in /home/grzanka/.conda/envs/pytriptest2/lib/python3.7/site-packages (from kiwisolver>=1.0.1->matplotlib->pytrip98) (45.1.0.post20200127)
Installing collected packages: pydicom, pyparsing, six, cycler, python-dateutil, kiwisolver, matplotlib, pytrip98
Successfully installed cycler-0.10.0 kiwisolver-1.1.0 matplotlib-3.1.3 pydicom-1.4.1 pyparsing-2.4.6 python-dateutil-2.8.1 pytrip98-2.6.0 six-1.14.0
(pytriptest2) grzanka@grzanka-VirtualBox:~/Downloads$ dicom2trip --version
ModuleNotFoundError: No module named 'numpy.core._multiarray_umath'
Traceback (most recent call last):
  File "/home/grzanka/.conda/envs/pytriptest2/bin/dicom2trip", line 5, in <module>
    from pytrip.utils.dicom2trip import main
  File "/home/grzanka/.conda/envs/pytriptest2/lib/python3.7/site-packages/pytrip/__init__.py", line 29, in <module>
    from pytrip.dos import DosCube
  File "/home/grzanka/.conda/envs/pytriptest2/lib/python3.7/site-packages/pytrip/dos.py", line 47, in <module>
    import pytriplib
ImportError: numpy.core.multiarray failed to import
```

**Comment by grzanka** [comment]
Funny, as numpy 1.16 works:
```
(pytriptest2) grzanka@grzanka-VirtualBox:~/Downloads$ pip install "numpy==1.16.0"
Collecting numpy==1.16.0
  Downloading numpy-1.16.0-cp37-cp37m-manylinux1_x86_64.whl (17.3 MB)
     |████████████████████████████████| 17.3 MB 454 kB/s 
Installing collected packages: numpy
  Attempting uninstall: numpy
    Found existing installation: numpy 1.18.1
    Uninstalling numpy-1.18.1:
      Successfully uninstalled numpy-1.18.1
Successfully installed numpy-1.16.0
(pytriptest2) grzanka@grzanka-VirtualBox:~/Downloads$ dicom2trip --version
2.6.0
```

**Comment by grzanka** [comment]
Interesting: the error is present on python 3.7, but no problems seem to arise on python 3.4:

python 3.4
```
(numpytest1) grzanka@grzanka-VirtualBox:~$ pip install "numpy<1.15"
Collecting numpy<1.15
  Cache entry deserialization failed, entry ignored
  Downloading https://files.pythonhosted.org/packages/99/a7/755f57ff4e5aa74f55479fc47a35d186d2613dc80b1625629c7b82a12ca9/numpy-1.14.6-cp34-cp34m-manylinux1_x86_64.whl (13.8MB)
    100% |████████████████████████████████| 13.8MB 130kB/s 
Installing collected packages: numpy
Successfully installed numpy-1.14.6
You are using pip version 9.0.1, however version 20.0.2 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
(numpytest1) grzanka@grzanka-VirtualBox:~$ pip install pytrip98
Collecting pytrip98
  Cache entry deserialization failed, entry ignored
  Using cached https://files.pythonhosted.org/packages/29/6c/3e62d5237b018e9d446a871d38660d176bd05127312168bf8bbcc30935b9/pytrip98-2.6.1-cp34-cp34m-manylinux1_x86_64.whl
Collecting pydicom (from pytrip98)
  Cache entry deserialization failed, entry ignored
  Using cached https://files.pythonhosted.org/packages/c0/ea/b05a0051a579acc8026e46a889354774a0da9d31f42aaa1af35a1f0e4a43/pydicom-1.4.1-py2.py3-none-any.whl
Requirement already satisfied: numpy in ./.conda/envs/numpytest1/lib/python3.4/site-packages (from pytrip98)
Collecting matplotlib (from pytrip98)
  Cache entry deserialization failed, entry ignored
  Using cached https://files.pythonhosted.org/packages/46/be/2c59876e9796d51a5c86c92e0161d2d47e4674211177ba15bff3b669f459/matplotlib-2.2.5-cp34-cp34m-manylinux1_x86_64.whl
Collecting python-dateutil>=2.1 (from matplotlib->pytrip98)
  Cache entry deserialization failed, entry ignored
  Using cached https://files.pythonhosted.org/packages/d4/70/d60450c3dd48ef87586924207ae8907090de0b306af2bce5d134d78615cb/python_dateutil-2.8.1-py2.py3-none-any.whl
Collecting pytz (from matplotlib->pytrip98)
  Using cached https://files.pythonhosted.org/packages/e7/f9/f0b53f88060247251bf481fa6ea62cd0d25bf1b11a87888e53ce5b7c8ad2/pytz-2019.3-py2.py3-none-any.whl
Collecting kiwisolver>=1.0.1 (from matplotlib->pytrip98)
  Cache entry deserialization failed, entry ignored
  Using cached https://files.pythonhosted.org/packages/04/73/69c86f3c617ea80d25f4ba7af3e5ce9bad72a4d024c2e7dc94524f8cbefa/kiwisolver-1.1.0-cp34-cp34m-manylinux1_x86_64.whl
Collecting pyparsing!=2.0.4,!=2.1.2,!=2.1.6,>=2.0.1 (from matplotlib->pytrip98)
  Cache entry deserialization failed, entry ignored
  Using cached https://files.pythonhosted.org/packages/5d/bc/1e58593167fade7b544bfe9502a26dc860940a79ab306e651e7f13be68c2/pyparsing-2.4.6-py2.py3-none-any.whl
Collecting cycler>=0.10 (from matplotlib->pytrip98)
  Cache entry deserialization failed, entry ignored
  Using cached https://files.pythonhosted.org/packages/f7/d2/e07d3ebb2bd7af696440ce7e754c59dd546ffe1bbe732c8ab68b9c834e61/cycler-0.10.0-py2.py3-none-any.whl
Collecting six>=1.10 (from matplotlib->pytrip98)
  Cache entry deserialization failed, entry ignored
  Using cached https://files.pythonhosted.org/packages/65/eb/1f97cb97bfc2390a276969c6fae16075da282f5058082d4cb10c6c5c1dba/six-1.14.0-py2.py3-none-any.whl
Requirement already satisfied: setuptools in ./.conda/envs/numpytest1/lib/python3.4/site-packages/setuptools-27.2.0-py3.4.egg (from kiwisolver>=1.0.1->matplotlib->pytrip98)
Installing collected packages: pydicom, six, python-dateutil, pytz, kiwisolver, pyparsing, cycler, matplotlib, pytrip98
Successfully installed cycler-0.10.0 kiwisolver-1.1.0 matplotlib-2.2.5 pydicom-1.4.1 pyparsing-2.4.6 python-dateutil-2.8.1 pytrip98-2.6.1 pytz-2019.3 six-1.14.0
You are using pip version 9.0.1, however version 20.0.2 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
(numpytest1) grzanka@grzanka-VirtualBox:~$ cubeslice --version
2.6.1
(numpytest1) grzanka@grzanka-VirtualBox:~$ python -V
Python 3.4.5 :: Continuum Analytics, Inc.
```

python 3.5
```
(numpytest2) grzanka@grzanka-VirtualBox:~$ pip install "numpy<1.15"
Collecting numpy<1.15
  Downloading https://files.pythonhosted.org/packages/43/f4/ffc029e0ffe001746b288f80e9b2143dafe442a3e87ac1fb9038964d72ab/numpy-1.14.6-cp35-cp35m-manylinux1_x86_64.whl (13.8MB)
    100% |████████████████████████████████| 13.8MB 3.6MB/s 
Installing collected packages: numpy
Successfully installed numpy-1.14.6
You are using pip version 10.0.1, however version 20.0.2 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
(numpytest2) grzanka@grzanka-VirtualBox:~$ pip install pytrip98
Collecting pytrip98
  Downloading https://files.pythonhosted.org/packages/7e/b2/a0ab1078043f47a8e63585d9a48124d870132555c9ab0d06ca24997f80dc/pytrip98-2.6.1-cp35-cp35m-manylinux1_x86_64.whl (214kB)
    100% |████████████████████████████████| 215kB 3.9MB/s 
Collecting pydicom (from pytrip98)
  Using cached https://files.pythonhosted.org/packages/c0/ea/b05a0051a579acc8026e46a889354774a0da9d31f42aaa1af35a1f0e4a43/pydicom-1.4.1-py2.py3-none-any.whl
Collecting matplotlib (from pytrip98)
  Downloading https://files.pythonhosted.org/packages/89/61/465fb3bfba684b0f53b5c4829c3c89e86e6fe9fdcdfda93e38f1788090f0/matplotlib-3.0.3-cp35-cp35m-manylinux1_x86_64.whl (13.0MB)
    100% |████████████████████████████████| 13.0MB 1.9MB/s 
Requirement already satisfied: numpy in ./.conda/envs/numpytest2/lib/python3.5/site-packages (from pytrip98) (1.14.6)
Collecting python-dateutil>=2.1 (from matplotlib->pytrip98)
  Using cached https://files.pythonhosted.org/packages/d4/70/d60450c3dd48ef87586924207ae8907090de0b306af2bce5d134d78615cb/python_dateutil-2.8.1-py2.py3-none-any.whl
Collecting kiwisolver>=1.0.1 (from matplotlib->pytrip98)
  Downloading https://files.pythonhosted.org/packages/ee/18/4cd2e84c6aff0c6a50479118083d20b9e676e5175a913c0ea76d700fc244/kiwisolver-1.1.0-cp35-cp35m-manylinux1_x86_64.whl (90kB)
    100% |████████████████████████████████| 92kB 31.1MB/s 
Collecting pyparsing!=2.0.4,!=2.1.2,!=2.1.6,>=2.0.1 (from matplotlib->pytrip98)
  Using cached https://files.pythonhosted.org/packages/5d/bc/1e58593167fade7b544bfe9502a26dc860940a79ab306e651e7f13be68c2/pyparsing-2.4.6-py2.py3-none-any.whl
Collecting cycler>=0.10 (from matplotlib->pytrip98)
  Using cached https://files.pythonhosted.org/packages/f7/d2/e07d3ebb2bd7af696440ce7e754c59dd546ffe1bbe732c8ab68b9c834e61/cycler-0.10.0-py2.py3-none-any.whl
Collecting six>=1.5 (from python-dateutil>=2.1->matplotlib->pytrip98)
  Using cached https://files.pythonhosted.org/packages/65/eb/1f97cb97bfc2390a276969c6fae16075da282f5058082d4cb10c6c5c1dba/six-1.14.0-py2.py3-none-any.whl
Requirement already satisfied: setuptools in ./.conda/envs/numpytest2/lib/python3.5/site-packages (from kiwisolver>=1.0.1->matplotlib->pytrip98) (40.2.0)
Installing collected packages: pydicom, six, python-dateutil, kiwisolver, pyparsing, cycler, matplotlib, pytrip98
Successfully installed cycler-0.10.0 kiwisolver-1.1.0 matplotlib-3.0.3 pydicom-1.4.1 pyparsing-2.4.6 python-dateutil-2.8.1 pytrip98-2.6.1 six-1.14.0
You are using pip version 10.0.1, however version 20.0.2 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
(numpytest2) grzanka@grzanka-VirtualBox:~$ cubeslice --version
ImportError: No module named 'numpy.core._multiarray_umath'
Traceback (most recent call last):
  File "/home/grzanka/.conda/envs/numpytest2/bin/cubeslice", line 7, in <module>
    from pytrip.utils.cubeslice import main
  File "/home/grzanka/.conda/envs/numpytest2/lib/python3.5/site-packages/pytrip/__init__.py", line 29, in <module>
    from pytrip.dos import DosCube
  File "/home/grzanka/.conda/envs/numpytest2/lib/python3.5/site-packages/pytrip/dos.py", line 47, in <module>
    import pytriplib
ImportError: numpy.core.multiarray failed to import
```

**Comment by grzanka** [comment]
Interesting summary of numpy ABI is here:
https://github.com/numpy/numpy/blob/36a2bf0ce8b072d557af5b58a9003a6bc72caaef/numpy/core/code_generators/cversions.txt

```
# Version 12 (NumPy 1.14) Added PyArray_ResolveWritebackIfCopy,
# PyArray_SetWritebackIfCopyBase and deprecated PyArray_SetUpdateIfCopyBase.
# Version 12 (NumPy 1.15) No change.
0x0000000c = a1bc756c5782853ec2e3616cf66869d8

# Version 13 (NumPy 1.16)
# Deprecate PyArray_SetNumericOps and PyArray_GetNumericOps,
# Add fields core_dim_flags and core_dim_sizes to PyUFuncObject.
# Add PyUFunc_FromFuncAndDataAndSignatureAndIdentity to ufunc_funcs_api.
# Version 13 (NumPy 1.17) No change.
# Version 13 (NumPy 1.18) No change.
# Version 13 (NumPy 1.19) No change.
0x0000000d = 5b0e8bbded00b166125974fc71e80a33
```

It looks that the problem is between numpy v 1.15 and numpy 1.16 when ABI has changed between 12 (0x0000000c) and 13 (0x0000000d).

**Comment by grzanka** [comment]
Check in Python:
```
Python 3.7.6 (default, Jan  8 2020, 19:59:22) 
[GCC 7.3.0] :: Anaconda, Inc. on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import numpy as np
>>> print("{:x}".format(np.core._multiarray_umath._get_ndarray_c_version()))
1000009
>>> np.__version__
'1.18.1'
```
