### ISSUE TITLE
Add support for MacOSX

### ISSUE THREAD

**Issue by grzanka** [pytrip/pytrip#587]
```
(1) Leszeks-MacBook-Air:~ grzanka$ pip install pytrip98
Collecting pytrip98
  Downloading https://files.pythonhosted.org/packages/3c/82/07e5fd1861d54774b9ef3bdcf0a746106417ce1a30281ff818717e0a483e/pytrip98-3.3.0.tar.gz (120kB)
     |████████████████████████████████| 122kB 2.3MB/s 
    ERROR: Command errored out with exit status 1:
     command: /Users/grzanka/tmp/1/bin/python3 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/5z/b4c5p4590qb2w83r5h3z76p00000gn/T/pip-install-m_m9fm7p/pytrip98/setup.py'"'"'; __file__='"'"'/private/var/folders/5z/b4c5p4590qb2w83r5h3z76p00000gn/T/pip-install-m_m9fm7p/pytrip98/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base pip-egg-info
         cwd: /private/var/folders/5z/b4c5p4590qb2w83r5h3z76p00000gn/T/pip-install-m_m9fm7p/pytrip98/
    Complete output (97 lines):
    fatal: not a git repository (or any of the parent directories): .git
    fatal: not a git repository (or any of the parent directories): .git
    Processing numpy/random/_bounded_integers.pxd.in
    Processing numpy/random/_philox.pyx
    Traceback (most recent call last):
      File "/var/folders/5z/b4c5p4590qb2w83r5h3z76p00000gn/T/easy_install-xw6a0zpe/numpy-1.21.2/tools/cythonize.py", line 59, in process_pyx
        import Cython
    ModuleNotFoundError: No module named 'Cython'
    
    The above exception was the direct cause of the following exception:
    
    Traceback (most recent call last):
      File "/var/folders/5z/b4c5p4590qb2w83r5h3z76p00000gn/T/easy_install-xw6a0zpe/numpy-1.21.2/tools/cythonize.py", line 240, in <module>
        main()
      File "/var/folders/5z/b4c5p4590qb2w83r5h3z76p00000gn/T/easy_install-xw6a0zpe/numpy-1.21.2/tools/cythonize.py", line 236, in main
        find_process_files(root_dir)
      File "/var/folders/5z/b4c5p4590qb2w83r5h3z76p00000gn/T/easy_install-xw6a0zpe/numpy-1.21.2/tools/cythonize.py", line 227, in find_process_files
        process(root_dir, fromfile, tofile, function, hash_db)
      File "/var/folders/5z/b4c5p4590qb2w83r5h3z76p00000gn/T/easy_install-xw6a0zpe/numpy-1.21.2/tools/cythonize.py", line 193, in process
        processor_function(fromfile, tofile)
      File "/var/folders/5z/b4c5p4590qb2w83r5h3z76p00000gn/T/easy_install-xw6a0zpe/numpy-1.21.2/tools/cythonize.py", line 66, in process_pyx
        raise OSError(msg) from e
    OSError: Cython needs to be installed in Python as a module
    Running from numpy source directory.
    Traceback (most recent call last):
      File "/Users/grzanka/tmp/1/lib/python3.8/site-packages/setuptools/sandbox.py", line 154, in save_modules
        yield saved
      File "/Users/grzanka/tmp/1/lib/python3.8/site-packages/setuptools/sandbox.py", line 195, in setup_context
        yield
      File "/Users/grzanka/tmp/1/lib/python3.8/site-packages/setuptools/sandbox.py", line 250, in run_setup
        _execfile(setup_script, ns)
      File "/Users/grzanka/tmp/1/lib/python3.8/site-packages/setuptools/sandbox.py", line 45, in _execfile
        exec(code, globals, locals)
      File "/var/folders/5z/b4c5p4590qb2w83r5h3z76p00000gn/T/easy_install-xw6a0zpe/numpy-1.21.2/setup.py", line 448, in <module>
      File "/var/folders/5z/b4c5p4590qb2w83r5h3z76p00000gn/T/easy_install-xw6a0zpe/numpy-1.21.2/setup.py", line 430, in setup_package
      File "/var/folders/5z/b4c5p4590qb2w83r5h3z76p00000gn/T/easy_install-xw6a0zpe/numpy-1.21.2/setup.py", line 236, in generate_cython
    RuntimeError: Running cythonize failed!
    
    During handling of the above exception, another exception occurred:
    
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/5z/b4c5p4590qb2w83r5h3z76p00000gn/T/pip-install-m_m9fm7p/pytrip98/setup.py", line 124, in <module>
        setuptools.setup(
      File "/Users/grzanka/tmp/1/lib/python3.8/site-packages/setuptools/__init__.py", line 144, in setup
        _install_setup_requires(attrs)
      File "/Users/grzanka/tmp/1/lib/python3.8/site-packages/setuptools/__init__.py", line 139, in _install_setup_requires
        dist.fetch_build_eggs(dist.setup_requires)
      File "/Users/grzanka/tmp/1/lib/python3.8/site-packages/setuptools/dist.py", line 716, in fetch_build_eggs
        resolved_dists = pkg_resources.working_set.resolve(
      File "/Users/grzanka/tmp/1/lib/python3.8/site-packages/pkg_resources/__init__.py", line 780, in resolve
        dist = best[req.key] = env.best_match(
      File "/Users/grzanka/tmp/1/lib/python3.8/site-packages/pkg_resources/__init__.py", line 1065, in best_match
        return self.obtain(req, installer)
      File "/Users/grzanka/tmp/1/lib/python3.8/site-packages/pkg_resources/__init__.py", line 1077, in obtain
        return installer(requirement)
      File "/Users/grzanka/tmp/1/lib/python3.8/site-packages/setuptools/dist.py", line 786, in fetch_build_egg
        return cmd.easy_install(req)
      File "/Users/grzanka/tmp/1/lib/python3.8/site-packages/setuptools/command/easy_install.py", line 679, in easy_install
        return self.install_item(spec, dist.location, tmpdir, deps)
      File "/Users/grzanka/tmp/1/lib/python3.8/site-packages/setuptools/command/easy_install.py", line 705, in install_item
        dists = self.install_eggs(spec, download, tmpdir)
      File "/Users/grzanka/tmp/1/lib/python3.8/site-packages/setuptools/command/easy_install.py", line 890, in install_eggs
        return self.build_and_install(setup_script, setup_base)
      File "/Users/grzanka/tmp/1/lib/python3.8/site-packages/setuptools/command/easy_install.py", line 1158, in build_and_install
        self.run_setup(setup_script, setup_base, args)
      File "/Users/grzanka/tmp/1/lib/python3.8/site-packages/setuptools/command/easy_install.py", line 1144, in run_setup
        run_setup(setup_script, args)
      File "/Users/grzanka/tmp/1/lib/python3.8/site-packages/setuptools/sandbox.py", line 253, in run_setup
        raise
      File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/contextlib.py", line 131, in __exit__
        self.gen.throw(type, value, traceback)
      File "/Users/grzanka/tmp/1/lib/python3.8/site-packages/setuptools/sandbox.py", line 195, in setup_context
        yield
      File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/contextlib.py", line 131, in __exit__
        self.gen.throw(type, value, traceback)
      File "/Users/grzanka/tmp/1/lib/python3.8/site-packages/setuptools/sandbox.py", line 166, in save_modules
        saved_exc.resume()
      File "/Users/grzanka/tmp/1/lib/python3.8/site-packages/setuptools/sandbox.py", line 141, in resume
        six.reraise(type, exc, self._tb)
      File "/Users/grzanka/tmp/1/lib/python3.8/site-packages/setuptools/_vendor/six.py", line 685, in reraise
        raise value.with_traceback(tb)
      File "/Users/grzanka/tmp/1/lib/python3.8/site-packages/setuptools/sandbox.py", line 154, in save_modules
        yield saved
      File "/Users/grzanka/tmp/1/lib/python3.8/site-packages/setuptools/sandbox.py", line 195, in setup_context
        yield
      File "/Users/grzanka/tmp/1/lib/python3.8/site-packages/setuptools/sandbox.py", line 250, in run_setup
        _execfile(setup_script, ns)
      File "/Users/grzanka/tmp/1/lib/python3.8/site-packages/setuptools/sandbox.py", line 45, in _execfile
        exec(code, globals, locals)
      File "/var/folders/5z/b4c5p4590qb2w83r5h3z76p00000gn/T/easy_install-xw6a0zpe/numpy-1.21.2/setup.py", line 448, in <module>
      File "/var/folders/5z/b4c5p4590qb2w83r5h3z76p00000gn/T/easy_install-xw6a0zpe/numpy-1.21.2/setup.py", line 430, in setup_package
      File "/var/folders/5z/b4c5p4590qb2w83r5h3z76p00000gn/T/easy_install-xw6a0zpe/numpy-1.21.2/setup.py", line 236, in generate_cython
    RuntimeError: Running cythonize failed!
    GIT_REVISION
    GIT_REVISION
    Cythonizing sources
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
WARNING: You are using pip version 19.2.3, however version 21.2.4 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
(1) Leszeks-MacBook-Air:~ grzanka$ python3 -V
Python 3.8.2
```

**Comment by grzanka** [comment]
Fixed with #595
