### ISSUE TITLE
cannot run current master as module

### ISSUE THREAD

**Issue by nbassler** [pytrip/pytrip#720]
```
(pytrip) bassler@baslup:~/Projects/pytrip$ git pull
Updating 102ec1b..afbcca0
Fast-forward
 .github/workflows/main.yml | 10 +++++-----
 1 file changed, 5 insertions(+), 5 deletions(-)

(pytrip) bassler@baslup:~/Projects/pytrip$ PYTHONPATH=. python3
Python 3.11.2 (main, Mar 13 2023, 12:18:29) [GCC 12.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import pytrip as pt
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/bassler/Projects/pytrip/pytrip/__init__.py", line 29, in <module>
    from pytrip.vdx import VdxCube, Voi
  File "/home/bassler/Projects/pytrip/pytrip/vdx.py", line 38, in <module>
    from pytrip.res.contour import create_contour
  File "/home/bassler/Projects/pytrip/pytrip/res/contour.py", line 8, in <module>
    from pytrip import _cntr
ImportError: cannot import name '_cntr' from partially initialized module 'pytrip' (most likely due to a circular import) (/home/bassler/Projects/pytrip/pytrip/__init__.py)

>>> 
```

**Comment by grzanka** [comment]
What if you install pytrip using pip from pypy in fresh venv ?

**Comment by nbassler** [comment]
Says so.
