### ISSUE TITLE
Problem reading dicom files with python3

### ISSUE THREAD

**Issue by grzanka** [pytrip/pytrip#73]
It looks that not all code was ported properly to python3

```
# grzanka at gajewski-dell in /tmp [14:14:16]
→ pip3 install pytrip98 --user
Collecting pytrip98
  Downloading pytrip98-1.1.0-cp34-cp34m-manylinux1_x86_64.whl (131kB)
    100% |████████████████████████████████| 133kB 1.1MB/s 
Requirement already satisfied (use --upgrade to upgrade): scipy in /home/grzanka/.local/lib/python3.4/site-packages (from pytrip98)
Requirement already satisfied (use --upgrade to upgrade): numpy in /usr/local/lib/python3.4/dist-packages (from pytrip98)
Requirement already satisfied (use --upgrade to upgrade): matplotlib in /usr/local/lib/python3.4/dist-packages (from pytrip98)
Requirement already satisfied (use --upgrade to upgrade): pydicom in /usr/local/lib/python3.4/dist-packages (from pytrip98)
Requirement already satisfied (use --upgrade to upgrade): python-dateutil in /usr/local/lib/python3.4/dist-packages (from matplotlib->pytrip98)
Requirement already satisfied (use --upgrade to upgrade): pytz in /usr/local/lib/python3.4/dist-packages (from matplotlib->pytrip98)
Requirement already satisfied (use --upgrade to upgrade): cycler in /usr/local/lib/python3.4/dist-packages (from matplotlib->pytrip98)
Requirement already satisfied (use --upgrade to upgrade): pyparsing!=2.0.4,>=1.5.6 in /usr/local/lib/python3.4/dist-packages (from matplotlib->pytrip98)
Requirement already satisfied (use --upgrade to upgrade): six>=1.5 in /usr/local/lib/python3.4/dist-packages (from python-dateutil->matplotlib->pytrip98)
Installing collected packages: pytrip98
Successfully installed pytrip98-1.1.0

# grzanka at gajewski-dell in /tmp [14:14:25]
→ git clone https://github.com/pytrip/testdata.git
Cloning into 'testdata'...
remote: Counting objects: 181, done.
remote: Compressing objects: 100% (178/178), done.
remote: Total 181 (delta 1), reused 177 (delta 0), pack-reused 0
Receiving objects: 100% (181/181), 34.19 MiB | 10.27 MiB/s, done.
Resolving deltas: 100% (1/1), done.
Checking connectivity... done.

# grzanka at gajewski-dell in /tmp [14:15:05]
→ ~/.local/bin/dicom2trip testdata/DICOM/HIT/CT out
Traceback (most recent call last):
  File "/home/grzanka/.local/bin/dicom2trip", line 11, in <module>
    sys.exit(main())
  File "/home/grzanka/.local/lib/python3.4/site-packages/pytrip/utils/dicom2trip.py", line 17, in main
    dcm = dicomhelper.read_dicom_folder(args[0])
  File "/home/grzanka/.local/lib/python3.4/site-packages/pytrip/dicomhelper.py", line 56, in read_dicom_folder
    data["images"].sort(cmp=compare_dicom_ct)
TypeError: 'cmp' is an invalid keyword argument for this function
```

**Comment by grzanka** [comment]
Fixed in PR #74
