### ISSUE TITLE
Pytrip doesn't convert properly custom made cubes into dicom

### ISSUE THREAD

**Issue by grzanka** [pytrip/pytrip#77]
First, let us create empty cube:

```
→ cat bug.py 
from pytrip.ctx import CtxCube
c = CtxCube()
c.create_empty_cube(
    value=-1024,
    dimx=10,
    dimy=20,
    dimz=30,
    pixel_size=1,
    slice_distance=1)
c.write("tmp")
→ cat python3 bug.py
→ cat tmp.hed 
version 2.0
modality CT
created_by pytrip
creation_info create by pytrip
primary_view transversal
data_type integer
num_bytes 2
byte_order vms
patient_name Anonyme
slice_dimension 30
pixel_size 1
slice_distance 1
slice_number 30
xoffset 0
dimx 10
yoffset 0
dimy 20
zoffset 0
dimz 30
z_table no
→ python3 ../pytrip/utils/trip2dicom.py tmp.hed 1/
	trip2dicom is a part of pytrip which was developed by 
	Niels Bassler (bassler@phys.au.dk) and 
	Jakob Toftegaard (jakob.toftegaard@gmail.com)
Convert CT images
Traceback (most recent call last):
  File "../pytrip/utils/trip2dicom.py", line 48, in <module>
    sys.exit(main(sys.argv[1:]))
  File "../pytrip/utils/trip2dicom.py", line 35, in main
    c.write_dicom(output_folder)
  File "/home/grzanka/PycharmProjects/pytrip/pytrip/ctx.py", line 97, in write_dicom
    dcm_list = self.create_dicom()
  File "/home/grzanka/PycharmProjects/pytrip/pytrip/ctx.py", line 83, in create_dicom
    pixel_array[:][:] = self.cube[i][:][:]
ValueError: could not broadcast input array from shape (20,10) into shape (10,20)

```

It looks the problem is here 
https://github.com/pytrip/pytrip/blob/master/pytrip/ctx.py#L81

```
  pixel_array = np.zeros((ds.Rows, ds.Columns), dtype=self.pydata_type)
```

Swapping Rows and Columns will solve the problem. Won't it create additional problems ?

It would be nice to write down how the Rows/Columns/Slices are mapped to X/Y/Z coordinates and indices.

**Comment by nbassler** [comment]
Only dimx == dimy is supported. If cols and rows must be swapped must still be checked though.
