### ISSUE TITLE
Pytrip doesn't save empty cube to dicom

### ISSUE THREAD

**Issue by grzanka** [pytrip/pytrip#78]
```
→ cat bug.py
from pytrip.ctx import CtxCube
c = CtxCube()
c.create_empty_cube(
    value=-1024,
    dimx=10,
    dimy=20,
    dimz=30,
    pixel_size=1,
    slice_distance=1)
c.write("tmp")
c.write_dicom("aa")                                                                                               
→ python3 bug.py                                  
Traceback (most recent call last):
  File "bug.py", line 11, in <module>
    c.write_dicom("aa")
  File "/home/grzanka/PycharmProjects/pytrip/pytrip/ctx.py", line 97, in write_dicom
    dcm_list = self.create_dicom()
  File "/home/grzanka/PycharmProjects/pytrip/pytrip/ctx.py", line 55, in create_dicom
    ds = self.create_dicom_base()
  File "/home/grzanka/PycharmProjects/pytrip/pytrip/cube.py", line 338, in create_dicom_base
    raise InputError("Header not loaded")
pytrip.error.InputError: 'Header not loaded'
```

**Comment by nbassler** [comment]
note that dimx == dimy

**Comment by nbassler** [comment]
related: #77
